/**
 ******************************************************************************
 * @addtogroup UAVObjects OpenPilot UAVObjects
 * @{ 
 * @addtogroup EscStatus EscStatus
 * @brief Various information from ESC.
 *
 * Autogenerated files and functions for EscStatus Object
 * @{ 
 *
 * @file       escstatus.c
 * @author     The OpenPilot Team, http://www.openpilot.org Copyright (C) 2010.
 * @brief      Implementation of the EscStatus object. This file has been 
 *             automatically generated by the UAVObjectGenerator.
 * 
 * @note       Object definition file: escstatus.xml. 
 *             This is an automatically generated file.
 *             DO NOT modify manually.
 *
 * @see        The GNU Public License (GPL) Version 3
 *
 *****************************************************************************/
/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */

#include "openpilot.h"
#include "escstatus.h"

// Private variables
static UAVObjHandle handle = NULL;

/**
 * Initialize object.
 * \return 0 Success
 * \return -1 Failure to initialize or -2 for already initialized
 */
int32_t EscStatusInitialize(void)
{
	// Don't set the handle to null if already registered
	if(UAVObjGetByID(ESCSTATUS_OBJID) != NULL)
		return -2;
	
	// Register object with the object manager
	handle = UAVObjRegister(ESCSTATUS_OBJID, ESCSTATUS_NAME, ESCSTATUS_METANAME, 0,
			ESCSTATUS_ISSINGLEINST, ESCSTATUS_ISSETTINGS, ESCSTATUS_NUMBYTES, &EscStatusSetDefaults);

	// Done
	if (handle != 0)
	{
		return 0;
	}
	else
	{
		return -1;
	}
}

/**
 * Initialize object fields and metadata with the default values.
 * If a default value is not specified the object fields
 * will be initialized to zero.
 */
void EscStatusSetDefaults(UAVObjHandle obj, uint16_t instId)
{
	EscStatusData data;
	UAVObjMetadata metadata;

	// Initialize object fields to their default values
	UAVObjGetInstanceData(obj, instId, &data);
	memset(&data, 0, sizeof(EscStatusData));

	UAVObjSetInstanceData(obj, instId, &data);

	// Initialize object metadata to their default values
	metadata.access = ACCESS_READWRITE;
	metadata.gcsAccess = ACCESS_READWRITE;
	metadata.telemetryAcked = 0;
	metadata.telemetryUpdateMode = UPDATEMODE_PERIODIC;
	metadata.telemetryUpdatePeriod = 1000;
	metadata.gcsTelemetryAcked = 0;
	metadata.gcsTelemetryUpdateMode = UPDATEMODE_MANUAL;
	metadata.gcsTelemetryUpdatePeriod = 0;
	metadata.loggingUpdateMode = UPDATEMODE_NEVER;
	metadata.loggingUpdatePeriod = 0;
	UAVObjSetMetadata(obj, &metadata);
}

/**
 * Get object handle
 */
UAVObjHandle EscStatusHandle()
{
	return handle;
}

/**
 * Get/Set object Functions
 */
void EscStatusSpeedSetpointSet( int16_t *NewSpeedSetpoint )
{
	UAVObjSetDataField(EscStatusHandle(), (void*)NewSpeedSetpoint, offsetof( EscStatusData, SpeedSetpoint), sizeof(int16_t));
}
void EscStatusSpeedSetpointGet( int16_t *NewSpeedSetpoint )
{
	UAVObjGetDataField(EscStatusHandle(), (void*)NewSpeedSetpoint, offsetof( EscStatusData, SpeedSetpoint), sizeof(int16_t));
}
void EscStatusCurrentSpeedSet( uint16_t *NewCurrentSpeed )
{
	UAVObjSetDataField(EscStatusHandle(), (void*)NewCurrentSpeed, offsetof( EscStatusData, CurrentSpeed), sizeof(uint16_t));
}
void EscStatusCurrentSpeedGet( uint16_t *NewCurrentSpeed )
{
	UAVObjGetDataField(EscStatusHandle(), (void*)NewCurrentSpeed, offsetof( EscStatusData, CurrentSpeed), sizeof(uint16_t));
}
void EscStatusCurrentSet( uint16_t *NewCurrent )
{
	UAVObjSetDataField(EscStatusHandle(), (void*)NewCurrent, offsetof( EscStatusData, Current), sizeof(uint16_t));
}
void EscStatusCurrentGet( uint16_t *NewCurrent )
{
	UAVObjGetDataField(EscStatusHandle(), (void*)NewCurrent, offsetof( EscStatusData, Current), sizeof(uint16_t));
}
void EscStatusTotalCurrentSet( uint16_t *NewTotalCurrent )
{
	UAVObjSetDataField(EscStatusHandle(), (void*)NewTotalCurrent, offsetof( EscStatusData, TotalCurrent), sizeof(uint16_t));
}
void EscStatusTotalCurrentGet( uint16_t *NewTotalCurrent )
{
	UAVObjGetDataField(EscStatusHandle(), (void*)NewTotalCurrent, offsetof( EscStatusData, TotalCurrent), sizeof(uint16_t));
}
void EscStatusKvSet( int16_t *NewKv )
{
	UAVObjSetDataField(EscStatusHandle(), (void*)NewKv, offsetof( EscStatusData, Kv), sizeof(int16_t));
}
void EscStatusKvGet( int16_t *NewKv )
{
	UAVObjGetDataField(EscStatusHandle(), (void*)NewKv, offsetof( EscStatusData, Kv), sizeof(int16_t));
}
void EscStatusBatterySet( uint16_t *NewBattery )
{
	UAVObjSetDataField(EscStatusHandle(), (void*)NewBattery, offsetof( EscStatusData, Battery), sizeof(uint16_t));
}
void EscStatusBatteryGet( uint16_t *NewBattery )
{
	UAVObjGetDataField(EscStatusHandle(), (void*)NewBattery, offsetof( EscStatusData, Battery), sizeof(uint16_t));
}
void EscStatusTotalMissedSet( uint16_t *NewTotalMissed )
{
	UAVObjSetDataField(EscStatusHandle(), (void*)NewTotalMissed, offsetof( EscStatusData, TotalMissed), sizeof(uint16_t));
}
void EscStatusTotalMissedGet( uint16_t *NewTotalMissed )
{
	UAVObjGetDataField(EscStatusHandle(), (void*)NewTotalMissed, offsetof( EscStatusData, TotalMissed), sizeof(uint16_t));
}
void EscStatusDutyCycleSet( uint8_t *NewDutyCycle )
{
	UAVObjSetDataField(EscStatusHandle(), (void*)NewDutyCycle, offsetof( EscStatusData, DutyCycle), sizeof(uint8_t));
}
void EscStatusDutyCycleGet( uint8_t *NewDutyCycle )
{
	UAVObjGetDataField(EscStatusHandle(), (void*)NewDutyCycle, offsetof( EscStatusData, DutyCycle), sizeof(uint8_t));
}
void EscStatusZcdFractionSet( uint8_t *NewZcdFraction )
{
	UAVObjSetDataField(EscStatusHandle(), (void*)NewZcdFraction, offsetof( EscStatusData, ZcdFraction), sizeof(uint8_t));
}
void EscStatusZcdFractionGet( uint8_t *NewZcdFraction )
{
	UAVObjGetDataField(EscStatusHandle(), (void*)NewZcdFraction, offsetof( EscStatusData, ZcdFraction), sizeof(uint8_t));
}
void EscStatusErrorSet( uint8_t *NewError )
{
	UAVObjSetDataField(EscStatusHandle(), (void*)NewError, offsetof( EscStatusData, Error), sizeof(uint8_t));
}
void EscStatusErrorGet( uint8_t *NewError )
{
	UAVObjGetDataField(EscStatusHandle(), (void*)NewError, offsetof( EscStatusData, Error), sizeof(uint8_t));
}


/**
 * @}
 */

