/**
 ******************************************************************************
 * @addtogroup UAVObjects OpenPilot UAVObjects
 * @{ 
 * @addtogroup GCSReceiver GCSReceiver 
 * @brief A receiver channel group carried over the telemetry link.
 *
 * Autogenerated files and functions for GCSReceiver Object
 
 * @{ 
 *
 * @file       gcsreceiver.h
 * @author     The OpenPilot Team, http://www.openpilot.org Copyright (C) 2010.
 * @brief      Implementation of the GCSReceiver object. This file has been 
 *             automatically generated by the UAVObjectGenerator.
 * 
 * @note       Object definition file: gcsreceiver.xml. 
 *             This is an automatically generated file.
 *             DO NOT modify manually.
 *
 * @see        The GNU Public License (GPL) Version 3
 *
 *****************************************************************************/
/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */

#ifndef GCSRECEIVER_H
#define GCSRECEIVER_H

// Object constants
#define GCSRECEIVER_OBJID 0xCC7E2BBC
#define GCSRECEIVER_NAME "GCSReceiver"
#define GCSRECEIVER_METANAME "GCSReceiverMeta"
#define GCSRECEIVER_ISSINGLEINST 1
#define GCSRECEIVER_ISSETTINGS 0
#define GCSRECEIVER_NUMBYTES sizeof(GCSReceiverData)

// Object access macros
/**
 * @function GCSReceiverGet(dataOut)
 * @brief Populate a GCSReceiverData object
 * @param[out] dataOut 
 */
#define GCSReceiverGet(dataOut) UAVObjGetData(GCSReceiverHandle(), dataOut)
#define GCSReceiverSet(dataIn) UAVObjSetData(GCSReceiverHandle(), dataIn)
#define GCSReceiverInstGet(instId, dataOut) UAVObjGetInstanceData(GCSReceiverHandle(), instId, dataOut)
#define GCSReceiverInstSet(instId, dataIn) UAVObjSetInstanceData(GCSReceiverHandle(), instId, dataIn)
#define GCSReceiverConnectQueue(queue) UAVObjConnectQueue(GCSReceiverHandle(), queue, EV_MASK_ALL_UPDATES)
#define GCSReceiverConnectCallback(cb) UAVObjConnectCallback(GCSReceiverHandle(), cb, EV_MASK_ALL_UPDATES)
#define GCSReceiverCreateInstance() UAVObjCreateInstance(GCSReceiverHandle(),&GCSReceiverSetDefaults)
#define GCSReceiverRequestUpdate() UAVObjRequestUpdate(GCSReceiverHandle())
#define GCSReceiverRequestInstUpdate(instId) UAVObjRequestInstanceUpdate(GCSReceiverHandle(), instId)
#define GCSReceiverUpdated() UAVObjUpdated(GCSReceiverHandle())
#define GCSReceiverInstUpdated(instId) UAVObjUpdated(GCSReceiverHandle(), instId)
#define GCSReceiverGetMetadata(dataOut) UAVObjGetMetadata(GCSReceiverHandle(), dataOut)
#define GCSReceiverSetMetadata(dataIn) UAVObjSetMetadata(GCSReceiverHandle(), dataIn)
#define GCSReceiverReadOnly() UAVObjReadOnly(GCSReceiverHandle())

// Object data
typedef struct {
    uint16_t Channel[6];

} __attribute__((packed)) GCSReceiverData;

// Field information
// Field Channel information
/* Number of elements for field Channel */
#define GCSRECEIVER_CHANNEL_NUMELEM 6


// Generic interface functions
int32_t GCSReceiverInitialize();
UAVObjHandle GCSReceiverHandle();
void GCSReceiverSetDefaults(UAVObjHandle obj, uint16_t instId);

// set/Get functions
extern void GCSReceiverChannelSet( uint16_t *NewChannel );
extern void GCSReceiverChannelGet( uint16_t *NewChannel );


#endif // GCSRECEIVER_H

/**
 * @}
 * @}
 */
