/**
 ******************************************************************************
 * @addtogroup UAVObjects OpenPilot UAVObjects
 * @{ 
 * @addtogroup GPSPosition GPSPosition
 * @brief Raw GPS data from @ref GPSModule.  Should only be used by @ref AHRSCommsModule.
 *
 * Autogenerated files and functions for GPSPosition Object
 * @{ 
 *
 * @file       gpsposition.c
 * @author     The OpenPilot Team, http://www.openpilot.org Copyright (C) 2010.
 * @brief      Implementation of the GPSPosition object. This file has been 
 *             automatically generated by the UAVObjectGenerator.
 * 
 * @note       Object definition file: gpsposition.xml. 
 *             This is an automatically generated file.
 *             DO NOT modify manually.
 *
 * @see        The GNU Public License (GPL) Version 3
 *
 *****************************************************************************/
/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */

#include "openpilot.h"
#include "gpsposition.h"

// Private variables
static UAVObjHandle handle = NULL;

/**
 * Initialize object.
 * \return 0 Success
 * \return -1 Failure to initialize or -2 for already initialized
 */
int32_t GPSPositionInitialize(void)
{
	// Don't set the handle to null if already registered
	if(UAVObjGetByID(GPSPOSITION_OBJID) != NULL)
		return -2;
	
	// Register object with the object manager
	handle = UAVObjRegister(GPSPOSITION_OBJID,
			GPSPOSITION_ISSINGLEINST, GPSPOSITION_ISSETTINGS, GPSPOSITION_NUMBYTES, &GPSPositionSetDefaults);

	// Done
	if (handle != 0)
	{
		return 0;
	}
	else
	{
		return -1;
	}
}

/**
 * Initialize object fields and metadata with the default values.
 * If a default value is not specified the object fields
 * will be initialized to zero.
 */
void GPSPositionSetDefaults(UAVObjHandle obj, uint16_t instId)
{
	GPSPositionData data;
	UAVObjMetadata metadata;

	// Initialize object fields to their default values
	UAVObjGetInstanceData(obj, instId, &data);
	memset(&data, 0, sizeof(GPSPositionData));

	UAVObjSetInstanceData(obj, instId, &data);

	// Initialize object metadata to their default values
	metadata.flags =
		ACCESS_READWRITE << UAVOBJ_ACCESS_SHIFT |
		ACCESS_READWRITE << UAVOBJ_GCS_ACCESS_SHIFT |
		0 << UAVOBJ_TELEMETRY_ACKED_SHIFT |
		0 << UAVOBJ_GCS_TELEMETRY_ACKED_SHIFT |
		UPDATEMODE_PERIODIC << UAVOBJ_TELEMETRY_UPDATE_MODE_SHIFT |
		UPDATEMODE_MANUAL << UAVOBJ_GCS_TELEMETRY_UPDATE_MODE_SHIFT;
	metadata.telemetryUpdatePeriod = 1000;
	metadata.gcsTelemetryUpdatePeriod = 0;
	metadata.loggingUpdatePeriod = 1000;
	UAVObjSetMetadata(obj, &metadata);
}

/**
 * Get object handle
 */
UAVObjHandle GPSPositionHandle()
{
	return handle;
}

/**
 * Get/Set object Functions
 */
void GPSPositionLatitudeSet( int32_t *NewLatitude )
{
	UAVObjSetDataField(GPSPositionHandle(), (void*)NewLatitude, offsetof( GPSPositionData, Latitude), sizeof(int32_t));
}
void GPSPositionLatitudeGet( int32_t *NewLatitude )
{
	UAVObjGetDataField(GPSPositionHandle(), (void*)NewLatitude, offsetof( GPSPositionData, Latitude), sizeof(int32_t));
}
void GPSPositionLongitudeSet( int32_t *NewLongitude )
{
	UAVObjSetDataField(GPSPositionHandle(), (void*)NewLongitude, offsetof( GPSPositionData, Longitude), sizeof(int32_t));
}
void GPSPositionLongitudeGet( int32_t *NewLongitude )
{
	UAVObjGetDataField(GPSPositionHandle(), (void*)NewLongitude, offsetof( GPSPositionData, Longitude), sizeof(int32_t));
}
void GPSPositionAltitudeSet( float *NewAltitude )
{
	UAVObjSetDataField(GPSPositionHandle(), (void*)NewAltitude, offsetof( GPSPositionData, Altitude), sizeof(float));
}
void GPSPositionAltitudeGet( float *NewAltitude )
{
	UAVObjGetDataField(GPSPositionHandle(), (void*)NewAltitude, offsetof( GPSPositionData, Altitude), sizeof(float));
}
void GPSPositionGeoidSeparationSet( float *NewGeoidSeparation )
{
	UAVObjSetDataField(GPSPositionHandle(), (void*)NewGeoidSeparation, offsetof( GPSPositionData, GeoidSeparation), sizeof(float));
}
void GPSPositionGeoidSeparationGet( float *NewGeoidSeparation )
{
	UAVObjGetDataField(GPSPositionHandle(), (void*)NewGeoidSeparation, offsetof( GPSPositionData, GeoidSeparation), sizeof(float));
}
void GPSPositionHeadingSet( float *NewHeading )
{
	UAVObjSetDataField(GPSPositionHandle(), (void*)NewHeading, offsetof( GPSPositionData, Heading), sizeof(float));
}
void GPSPositionHeadingGet( float *NewHeading )
{
	UAVObjGetDataField(GPSPositionHandle(), (void*)NewHeading, offsetof( GPSPositionData, Heading), sizeof(float));
}
void GPSPositionGroundspeedSet( float *NewGroundspeed )
{
	UAVObjSetDataField(GPSPositionHandle(), (void*)NewGroundspeed, offsetof( GPSPositionData, Groundspeed), sizeof(float));
}
void GPSPositionGroundspeedGet( float *NewGroundspeed )
{
	UAVObjGetDataField(GPSPositionHandle(), (void*)NewGroundspeed, offsetof( GPSPositionData, Groundspeed), sizeof(float));
}
void GPSPositionPDOPSet( float *NewPDOP )
{
	UAVObjSetDataField(GPSPositionHandle(), (void*)NewPDOP, offsetof( GPSPositionData, PDOP), sizeof(float));
}
void GPSPositionPDOPGet( float *NewPDOP )
{
	UAVObjGetDataField(GPSPositionHandle(), (void*)NewPDOP, offsetof( GPSPositionData, PDOP), sizeof(float));
}
void GPSPositionHDOPSet( float *NewHDOP )
{
	UAVObjSetDataField(GPSPositionHandle(), (void*)NewHDOP, offsetof( GPSPositionData, HDOP), sizeof(float));
}
void GPSPositionHDOPGet( float *NewHDOP )
{
	UAVObjGetDataField(GPSPositionHandle(), (void*)NewHDOP, offsetof( GPSPositionData, HDOP), sizeof(float));
}
void GPSPositionVDOPSet( float *NewVDOP )
{
	UAVObjSetDataField(GPSPositionHandle(), (void*)NewVDOP, offsetof( GPSPositionData, VDOP), sizeof(float));
}
void GPSPositionVDOPGet( float *NewVDOP )
{
	UAVObjGetDataField(GPSPositionHandle(), (void*)NewVDOP, offsetof( GPSPositionData, VDOP), sizeof(float));
}
void GPSPositionStatusSet( uint8_t *NewStatus )
{
	UAVObjSetDataField(GPSPositionHandle(), (void*)NewStatus, offsetof( GPSPositionData, Status), sizeof(uint8_t));
}
void GPSPositionStatusGet( uint8_t *NewStatus )
{
	UAVObjGetDataField(GPSPositionHandle(), (void*)NewStatus, offsetof( GPSPositionData, Status), sizeof(uint8_t));
}
void GPSPositionSatellitesSet( int8_t *NewSatellites )
{
	UAVObjSetDataField(GPSPositionHandle(), (void*)NewSatellites, offsetof( GPSPositionData, Satellites), sizeof(int8_t));
}
void GPSPositionSatellitesGet( int8_t *NewSatellites )
{
	UAVObjGetDataField(GPSPositionHandle(), (void*)NewSatellites, offsetof( GPSPositionData, Satellites), sizeof(int8_t));
}


/**
 * @}
 */

