/**
 ******************************************************************************
 * @addtogroup UAVObjects OpenPilot UAVObjects
 * @{ 
 * @addtogroup GyrosBias GyrosBias 
 * @brief The gyro data.
 *
 * Autogenerated files and functions for GyrosBias Object
 
 * @{ 
 *
 * @file       gyrosbias.h
 * @author     The OpenPilot Team, http://www.openpilot.org Copyright (C) 2010.
 * @brief      Implementation of the GyrosBias object. This file has been 
 *             automatically generated by the UAVObjectGenerator.
 * 
 * @note       Object definition file: gyrosbias.xml. 
 *             This is an automatically generated file.
 *             DO NOT modify manually.
 *
 * @see        The GNU Public License (GPL) Version 3
 *
 *****************************************************************************/
/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */

#ifndef GYROSBIAS_H
#define GYROSBIAS_H

// Object constants
#define GYROSBIAS_OBJID 0xE4B6F980
#define GYROSBIAS_NAME "GyrosBias"
#define GYROSBIAS_METANAME "GyrosBiasMeta"
#define GYROSBIAS_ISSINGLEINST 1
#define GYROSBIAS_ISSETTINGS 0
#define GYROSBIAS_NUMBYTES sizeof(GyrosBiasData)

// Object access macros
/**
 * @function GyrosBiasGet(dataOut)
 * @brief Populate a GyrosBiasData object
 * @param[out] dataOut 
 */
#define GyrosBiasGet(dataOut) UAVObjGetData(GyrosBiasHandle(), dataOut)
#define GyrosBiasSet(dataIn) UAVObjSetData(GyrosBiasHandle(), dataIn)
#define GyrosBiasInstGet(instId, dataOut) UAVObjGetInstanceData(GyrosBiasHandle(), instId, dataOut)
#define GyrosBiasInstSet(instId, dataIn) UAVObjSetInstanceData(GyrosBiasHandle(), instId, dataIn)
#define GyrosBiasConnectQueue(queue) UAVObjConnectQueue(GyrosBiasHandle(), queue, EV_MASK_ALL_UPDATES)
#define GyrosBiasConnectCallback(cb) UAVObjConnectCallback(GyrosBiasHandle(), cb, EV_MASK_ALL_UPDATES)
#define GyrosBiasCreateInstance() UAVObjCreateInstance(GyrosBiasHandle(),&GyrosBiasSetDefaults)
#define GyrosBiasRequestUpdate() UAVObjRequestUpdate(GyrosBiasHandle())
#define GyrosBiasRequestInstUpdate(instId) UAVObjRequestInstanceUpdate(GyrosBiasHandle(), instId)
#define GyrosBiasUpdated() UAVObjUpdated(GyrosBiasHandle())
#define GyrosBiasInstUpdated(instId) UAVObjUpdated(GyrosBiasHandle(), instId)
#define GyrosBiasGetMetadata(dataOut) UAVObjGetMetadata(GyrosBiasHandle(), dataOut)
#define GyrosBiasSetMetadata(dataIn) UAVObjSetMetadata(GyrosBiasHandle(), dataIn)
#define GyrosBiasReadOnly() UAVObjReadOnly(GyrosBiasHandle())

// Object data
typedef struct {
    float x;
    float y;
    float z;

} __attribute__((packed)) GyrosBiasData;

// Field information
// Field x information
// Field y information
// Field z information


// Generic interface functions
int32_t GyrosBiasInitialize();
UAVObjHandle GyrosBiasHandle();
void GyrosBiasSetDefaults(UAVObjHandle obj, uint16_t instId);

// set/Get functions
extern void GyrosBiasxSet( float *Newx );
extern void GyrosBiasxGet( float *Newx );
extern void GyrosBiasySet( float *Newy );
extern void GyrosBiasyGet( float *Newy );
extern void GyrosBiaszSet( float *Newz );
extern void GyrosBiaszGet( float *Newz );


#endif // GYROSBIAS_H

/**
 * @}
 * @}
 */
