/**
 ******************************************************************************
 * @addtogroup UAVObjects OpenPilot UAVObjects
 * @{ 
 * @addtogroup INSSettings INSSettings
 * @brief Settings for the INS to control the algorithm and what is updated
 *
 * Autogenerated files and functions for INSSettings Object
 * @{ 
 *
 * @file       inssettings.c
 * @author     The OpenPilot Team, http://www.openpilot.org Copyright (C) 2010.
 * @brief      Implementation of the INSSettings object. This file has been 
 *             automatically generated by the UAVObjectGenerator.
 * 
 * @note       Object definition file: inssettings.xml. 
 *             This is an automatically generated file.
 *             DO NOT modify manually.
 *
 * @see        The GNU Public License (GPL) Version 3
 *
 *****************************************************************************/
/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */

#include "openpilot.h"
#include "inssettings.h"

// Private variables
static UAVObjHandle handle = NULL;

/**
 * Initialize object.
 * \return 0 Success
 * \return -1 Failure to initialize or -2 for already initialized
 */
int32_t INSSettingsInitialize(void)
{
	// Don't set the handle to null if already registered
	if(UAVObjGetByID(INSSETTINGS_OBJID) != NULL)
		return -2;
	
	// Register object with the object manager
	handle = UAVObjRegister(INSSETTINGS_OBJID,
			INSSETTINGS_ISSINGLEINST, INSSETTINGS_ISSETTINGS, INSSETTINGS_NUMBYTES, &INSSettingsSetDefaults);

	// Done
	if (handle != 0)
	{
		return 0;
	}
	else
	{
		return -1;
	}
}

/**
 * Initialize object fields and metadata with the default values.
 * If a default value is not specified the object fields
 * will be initialized to zero.
 */
void INSSettingsSetDefaults(UAVObjHandle obj, uint16_t instId)
{
	INSSettingsData data;
	UAVObjMetadata metadata;

	// Initialize object fields to their default values
	UAVObjGetInstanceData(obj, instId, &data);
	memset(&data, 0, sizeof(INSSettingsData));
	data.accel_var[0] = 0.01;
	data.accel_var[1] = 0.01;
	data.accel_var[2] = 0.01;
	data.gyro_var[0] = 0.01;
	data.gyro_var[1] = 0.01;
	data.gyro_var[2] = 0.01;
	data.mag_var[0] = 0.01;
	data.mag_var[1] = 0.01;
	data.mag_var[2] = 10;
	data.gps_var[0] = 1;
	data.gps_var[1] = 1;
	data.baro_var = 1;
	data.MagBiasNullingRate = 0;
	data.ComputeGyroBias = 0;

	UAVObjSetInstanceData(obj, instId, &data);

	// Initialize object metadata to their default values
	metadata.flags =
		ACCESS_READWRITE << UAVOBJ_ACCESS_SHIFT |
		ACCESS_READWRITE << UAVOBJ_GCS_ACCESS_SHIFT |
		1 << UAVOBJ_TELEMETRY_ACKED_SHIFT |
		1 << UAVOBJ_GCS_TELEMETRY_ACKED_SHIFT |
		UPDATEMODE_ONCHANGE << UAVOBJ_TELEMETRY_UPDATE_MODE_SHIFT |
		UPDATEMODE_ONCHANGE << UAVOBJ_GCS_TELEMETRY_UPDATE_MODE_SHIFT;
	metadata.telemetryUpdatePeriod = 0;
	metadata.gcsTelemetryUpdatePeriod = 0;
	metadata.loggingUpdatePeriod = 0;
	UAVObjSetMetadata(obj, &metadata);
}

/**
 * Get object handle
 */
UAVObjHandle INSSettingsHandle()
{
	return handle;
}

/**
 * Get/Set object Functions
 */
void INSSettingsaccel_varSet( float *Newaccel_var )
{
	UAVObjSetDataField(INSSettingsHandle(), (void*)Newaccel_var, offsetof( INSSettingsData, accel_var), 3*sizeof(float));
}
void INSSettingsaccel_varGet( float *Newaccel_var )
{
	UAVObjGetDataField(INSSettingsHandle(), (void*)Newaccel_var, offsetof( INSSettingsData, accel_var), 3*sizeof(float));
}
void INSSettingsgyro_varSet( float *Newgyro_var )
{
	UAVObjSetDataField(INSSettingsHandle(), (void*)Newgyro_var, offsetof( INSSettingsData, gyro_var), 3*sizeof(float));
}
void INSSettingsgyro_varGet( float *Newgyro_var )
{
	UAVObjGetDataField(INSSettingsHandle(), (void*)Newgyro_var, offsetof( INSSettingsData, gyro_var), 3*sizeof(float));
}
void INSSettingsmag_varSet( float *Newmag_var )
{
	UAVObjSetDataField(INSSettingsHandle(), (void*)Newmag_var, offsetof( INSSettingsData, mag_var), 3*sizeof(float));
}
void INSSettingsmag_varGet( float *Newmag_var )
{
	UAVObjGetDataField(INSSettingsHandle(), (void*)Newmag_var, offsetof( INSSettingsData, mag_var), 3*sizeof(float));
}
void INSSettingsgps_varSet( float *Newgps_var )
{
	UAVObjSetDataField(INSSettingsHandle(), (void*)Newgps_var, offsetof( INSSettingsData, gps_var), 2*sizeof(float));
}
void INSSettingsgps_varGet( float *Newgps_var )
{
	UAVObjGetDataField(INSSettingsHandle(), (void*)Newgps_var, offsetof( INSSettingsData, gps_var), 2*sizeof(float));
}
void INSSettingsbaro_varSet( float *Newbaro_var )
{
	UAVObjSetDataField(INSSettingsHandle(), (void*)Newbaro_var, offsetof( INSSettingsData, baro_var), sizeof(float));
}
void INSSettingsbaro_varGet( float *Newbaro_var )
{
	UAVObjGetDataField(INSSettingsHandle(), (void*)Newbaro_var, offsetof( INSSettingsData, baro_var), sizeof(float));
}
void INSSettingsMagBiasNullingRateSet( float *NewMagBiasNullingRate )
{
	UAVObjSetDataField(INSSettingsHandle(), (void*)NewMagBiasNullingRate, offsetof( INSSettingsData, MagBiasNullingRate), sizeof(float));
}
void INSSettingsMagBiasNullingRateGet( float *NewMagBiasNullingRate )
{
	UAVObjGetDataField(INSSettingsHandle(), (void*)NewMagBiasNullingRate, offsetof( INSSettingsData, MagBiasNullingRate), sizeof(float));
}
void INSSettingsComputeGyroBiasSet( uint8_t *NewComputeGyroBias )
{
	UAVObjSetDataField(INSSettingsHandle(), (void*)NewComputeGyroBias, offsetof( INSSettingsData, ComputeGyroBias), sizeof(uint8_t));
}
void INSSettingsComputeGyroBiasGet( uint8_t *NewComputeGyroBias )
{
	UAVObjGetDataField(INSSettingsHandle(), (void*)NewComputeGyroBias, offsetof( INSSettingsData, ComputeGyroBias), sizeof(uint8_t));
}


/**
 * @}
 */

