/**
 ******************************************************************************
 * @addtogroup TauLabsCore Tau Labs Core components
 * @{
 * @addtogroup UAVObjects UAVObject set for this firmware
 * @{
 *
 * @file       onscreendisplaypagesettings2.c
 * @author     The OpenPilot Team, http://www.openpilot.org Copyright (C) 2010.
 * @author     Tau Labs, http://taulabs.org, Copyright (C) 2012-2013
 * @brief      Implementation of the OnScreenDisplayPageSettings2 object. This file has been 
 *             automatically generated by the UAVObjectGenerator.
 * 
 * @note       Object definition file: onscreendisplaypagesettings2.xml. 
 *             This is an automatically generated file.
 *             DO NOT modify manually.
 *
 * @see        The GNU Public License (GPL) Version 3
 *
 *****************************************************************************/
/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */

#include "openpilot.h"
#include "onscreendisplaypagesettings2.h"

// Private variables
static UAVObjHandle handle = NULL;

/**
 * Initialize object.
 * \return 0 Success
 * \return -1 Failure to initialize or -2 for already initialized
 */
int32_t OnScreenDisplayPageSettings2Initialize(void)
{
	// Don't set the handle to null if already registered
	if(UAVObjGetByID(ONSCREENDISPLAYPAGESETTINGS2_OBJID) != NULL)
		return -2;
	
	// Register object with the object manager
	handle = UAVObjRegister(ONSCREENDISPLAYPAGESETTINGS2_OBJID,
			ONSCREENDISPLAYPAGESETTINGS2_ISSINGLEINST, ONSCREENDISPLAYPAGESETTINGS2_ISSETTINGS, ONSCREENDISPLAYPAGESETTINGS2_NUMBYTES, &OnScreenDisplayPageSettings2SetDefaults);

	// Done
	if (handle != 0)
	{
		return 0;
	}
	else
	{
		return -1;
	}
}

/**
 * Initialize object fields and metadata with the default values.
 * If a default value is not specified the object fields
 * will be initialized to zero.
 */
void OnScreenDisplayPageSettings2SetDefaults(UAVObjHandle obj, uint16_t instId)
{
	OnScreenDisplayPageSettings2Data data;
	UAVObjMetadata metadata;

	// Initialize object fields to their default values
	UAVObjGetInstanceData(obj, instId, &data);
	memset(&data, 0, sizeof(OnScreenDisplayPageSettings2Data));
	data.AlarmPosX = 0;
	data.AlarmPosY = 220;
	data.AltitudeScalePos = 350;
	data.ArmStatusPosX = 0;
	data.ArmStatusPosY = 14;
	data.BatteryVoltPosX = 350;
	data.BatteryVoltPosY = 4;
	data.BatteryCurrentPosX = 350;
	data.BatteryCurrentPosY = 14;
	data.BatteryConsumedPosX = 350;
	data.BatteryConsumedPosY = 24;
	data.CompassPos = 15;
	data.CpuPosX = 0;
	data.CpuPosY = 210;
	data.FlightModePosX = 0;
	data.FlightModePosY = 4;
	data.GpsStatusPosX = 0;
	data.GpsStatusPosY = 230;
	data.GpsLatPosX = 210;
	data.GpsLatPosY = 230;
	data.GpsLonPosX = 350;
	data.GpsLonPosY = 230;
	data.HomeDistancePosX = 150;
	data.HomeDistancePosY = 210;
	data.RssiPosX = 150;
	data.RssiPosY = 195;
	data.SpeedScalePos = 0;
	data.TimePosX = 350;
	data.TimePosY = 220;
	data.Alarm = 1;
	data.AlarmFont = 0;
	data.AlarmAlign = 0;
	data.AltitudeScale = 1;
	data.AltitudeScaleAlign = 1;
	data.AltitudeScaleSource = 0;
	data.ArmStatus = 1;
	data.ArmStatusFont = 0;
	data.ArmStatusAlign = 0;
	data.ArtificialHorizon = 1;
	data.BatteryVolt = 1;
	data.BatteryVoltFont = 0;
	data.BatteryVoltAlign = 2;
	data.BatteryCurrent = 1;
	data.BatteryCurrentFont = 0;
	data.BatteryCurrentAlign = 2;
	data.BatteryConsumed = 1;
	data.BatteryConsumedFont = 0;
	data.BatteryConsumedAlign = 2;
	data.Compass = 1;
	data.CompassHomeDir = 1;
	data.Cpu = 0;
	data.CpuFont = 0;
	data.CpuAlign = 0;
	data.FlightMode = 1;
	data.FlightModeFont = 0;
	data.FlightModeAlign = 0;
	data.GpsStatus = 1;
	data.GpsStatusFont = 0;
	data.GpsStatusAlign = 0;
	data.GpsLat = 1;
	data.GpsLatFont = 0;
	data.GpsLatAlign = 0;
	data.GpsLon = 1;
	data.GpsLonFont = 0;
	data.GpsLonAlign = 2;
	data.HomeDistance = 1;
	data.HomeDistanceFont = 0;
	data.HomeDistanceAlign = 0;
	data.Rssi = 1;
	data.RssiFont = 0;
	data.RssiAlign = 0;
	data.SpeedScale = 1;
	data.SpeedScaleAlign = 0;
	data.SpeedScaleSource = 0;
	data.Time = 1;
	data.TimeFont = 0;
	data.TimeAlign = 2;

	UAVObjSetInstanceData(obj, instId, &data);

	// Initialize object metadata to their default values
	metadata.flags =
		ACCESS_READWRITE << UAVOBJ_ACCESS_SHIFT |
		ACCESS_READWRITE << UAVOBJ_GCS_ACCESS_SHIFT |
		1 << UAVOBJ_TELEMETRY_ACKED_SHIFT |
		1 << UAVOBJ_GCS_TELEMETRY_ACKED_SHIFT |
		UPDATEMODE_ONCHANGE << UAVOBJ_TELEMETRY_UPDATE_MODE_SHIFT |
		UPDATEMODE_ONCHANGE << UAVOBJ_GCS_TELEMETRY_UPDATE_MODE_SHIFT;
	metadata.telemetryUpdatePeriod = 0;
	metadata.gcsTelemetryUpdatePeriod = 0;
	metadata.loggingUpdatePeriod = 0;
	UAVObjSetMetadata(obj, &metadata);
}

/**
 * Get object handle
 */
UAVObjHandle OnScreenDisplayPageSettings2Handle()
{
	return handle;
}

/**
 * Get/Set object Functions
 */
void OnScreenDisplayPageSettings2AlarmPosXSet( int16_t *NewAlarmPosX )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewAlarmPosX, offsetof( OnScreenDisplayPageSettings2Data, AlarmPosX), sizeof(int16_t));
}
void OnScreenDisplayPageSettings2AlarmPosXGet( int16_t *NewAlarmPosX )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewAlarmPosX, offsetof( OnScreenDisplayPageSettings2Data, AlarmPosX), sizeof(int16_t));
}
void OnScreenDisplayPageSettings2AlarmPosYSet( int16_t *NewAlarmPosY )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewAlarmPosY, offsetof( OnScreenDisplayPageSettings2Data, AlarmPosY), sizeof(int16_t));
}
void OnScreenDisplayPageSettings2AlarmPosYGet( int16_t *NewAlarmPosY )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewAlarmPosY, offsetof( OnScreenDisplayPageSettings2Data, AlarmPosY), sizeof(int16_t));
}
void OnScreenDisplayPageSettings2AltitudeScalePosSet( int16_t *NewAltitudeScalePos )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewAltitudeScalePos, offsetof( OnScreenDisplayPageSettings2Data, AltitudeScalePos), sizeof(int16_t));
}
void OnScreenDisplayPageSettings2AltitudeScalePosGet( int16_t *NewAltitudeScalePos )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewAltitudeScalePos, offsetof( OnScreenDisplayPageSettings2Data, AltitudeScalePos), sizeof(int16_t));
}
void OnScreenDisplayPageSettings2ArmStatusPosXSet( int16_t *NewArmStatusPosX )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewArmStatusPosX, offsetof( OnScreenDisplayPageSettings2Data, ArmStatusPosX), sizeof(int16_t));
}
void OnScreenDisplayPageSettings2ArmStatusPosXGet( int16_t *NewArmStatusPosX )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewArmStatusPosX, offsetof( OnScreenDisplayPageSettings2Data, ArmStatusPosX), sizeof(int16_t));
}
void OnScreenDisplayPageSettings2ArmStatusPosYSet( int16_t *NewArmStatusPosY )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewArmStatusPosY, offsetof( OnScreenDisplayPageSettings2Data, ArmStatusPosY), sizeof(int16_t));
}
void OnScreenDisplayPageSettings2ArmStatusPosYGet( int16_t *NewArmStatusPosY )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewArmStatusPosY, offsetof( OnScreenDisplayPageSettings2Data, ArmStatusPosY), sizeof(int16_t));
}
void OnScreenDisplayPageSettings2BatteryVoltPosXSet( int16_t *NewBatteryVoltPosX )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewBatteryVoltPosX, offsetof( OnScreenDisplayPageSettings2Data, BatteryVoltPosX), sizeof(int16_t));
}
void OnScreenDisplayPageSettings2BatteryVoltPosXGet( int16_t *NewBatteryVoltPosX )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewBatteryVoltPosX, offsetof( OnScreenDisplayPageSettings2Data, BatteryVoltPosX), sizeof(int16_t));
}
void OnScreenDisplayPageSettings2BatteryVoltPosYSet( int16_t *NewBatteryVoltPosY )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewBatteryVoltPosY, offsetof( OnScreenDisplayPageSettings2Data, BatteryVoltPosY), sizeof(int16_t));
}
void OnScreenDisplayPageSettings2BatteryVoltPosYGet( int16_t *NewBatteryVoltPosY )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewBatteryVoltPosY, offsetof( OnScreenDisplayPageSettings2Data, BatteryVoltPosY), sizeof(int16_t));
}
void OnScreenDisplayPageSettings2BatteryCurrentPosXSet( int16_t *NewBatteryCurrentPosX )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewBatteryCurrentPosX, offsetof( OnScreenDisplayPageSettings2Data, BatteryCurrentPosX), sizeof(int16_t));
}
void OnScreenDisplayPageSettings2BatteryCurrentPosXGet( int16_t *NewBatteryCurrentPosX )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewBatteryCurrentPosX, offsetof( OnScreenDisplayPageSettings2Data, BatteryCurrentPosX), sizeof(int16_t));
}
void OnScreenDisplayPageSettings2BatteryCurrentPosYSet( int16_t *NewBatteryCurrentPosY )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewBatteryCurrentPosY, offsetof( OnScreenDisplayPageSettings2Data, BatteryCurrentPosY), sizeof(int16_t));
}
void OnScreenDisplayPageSettings2BatteryCurrentPosYGet( int16_t *NewBatteryCurrentPosY )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewBatteryCurrentPosY, offsetof( OnScreenDisplayPageSettings2Data, BatteryCurrentPosY), sizeof(int16_t));
}
void OnScreenDisplayPageSettings2BatteryConsumedPosXSet( int16_t *NewBatteryConsumedPosX )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewBatteryConsumedPosX, offsetof( OnScreenDisplayPageSettings2Data, BatteryConsumedPosX), sizeof(int16_t));
}
void OnScreenDisplayPageSettings2BatteryConsumedPosXGet( int16_t *NewBatteryConsumedPosX )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewBatteryConsumedPosX, offsetof( OnScreenDisplayPageSettings2Data, BatteryConsumedPosX), sizeof(int16_t));
}
void OnScreenDisplayPageSettings2BatteryConsumedPosYSet( int16_t *NewBatteryConsumedPosY )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewBatteryConsumedPosY, offsetof( OnScreenDisplayPageSettings2Data, BatteryConsumedPosY), sizeof(int16_t));
}
void OnScreenDisplayPageSettings2BatteryConsumedPosYGet( int16_t *NewBatteryConsumedPosY )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewBatteryConsumedPosY, offsetof( OnScreenDisplayPageSettings2Data, BatteryConsumedPosY), sizeof(int16_t));
}
void OnScreenDisplayPageSettings2CompassPosSet( int16_t *NewCompassPos )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewCompassPos, offsetof( OnScreenDisplayPageSettings2Data, CompassPos), sizeof(int16_t));
}
void OnScreenDisplayPageSettings2CompassPosGet( int16_t *NewCompassPos )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewCompassPos, offsetof( OnScreenDisplayPageSettings2Data, CompassPos), sizeof(int16_t));
}
void OnScreenDisplayPageSettings2CpuPosXSet( int16_t *NewCpuPosX )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewCpuPosX, offsetof( OnScreenDisplayPageSettings2Data, CpuPosX), sizeof(int16_t));
}
void OnScreenDisplayPageSettings2CpuPosXGet( int16_t *NewCpuPosX )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewCpuPosX, offsetof( OnScreenDisplayPageSettings2Data, CpuPosX), sizeof(int16_t));
}
void OnScreenDisplayPageSettings2CpuPosYSet( int16_t *NewCpuPosY )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewCpuPosY, offsetof( OnScreenDisplayPageSettings2Data, CpuPosY), sizeof(int16_t));
}
void OnScreenDisplayPageSettings2CpuPosYGet( int16_t *NewCpuPosY )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewCpuPosY, offsetof( OnScreenDisplayPageSettings2Data, CpuPosY), sizeof(int16_t));
}
void OnScreenDisplayPageSettings2FlightModePosXSet( int16_t *NewFlightModePosX )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewFlightModePosX, offsetof( OnScreenDisplayPageSettings2Data, FlightModePosX), sizeof(int16_t));
}
void OnScreenDisplayPageSettings2FlightModePosXGet( int16_t *NewFlightModePosX )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewFlightModePosX, offsetof( OnScreenDisplayPageSettings2Data, FlightModePosX), sizeof(int16_t));
}
void OnScreenDisplayPageSettings2FlightModePosYSet( int16_t *NewFlightModePosY )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewFlightModePosY, offsetof( OnScreenDisplayPageSettings2Data, FlightModePosY), sizeof(int16_t));
}
void OnScreenDisplayPageSettings2FlightModePosYGet( int16_t *NewFlightModePosY )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewFlightModePosY, offsetof( OnScreenDisplayPageSettings2Data, FlightModePosY), sizeof(int16_t));
}
void OnScreenDisplayPageSettings2GpsStatusPosXSet( int16_t *NewGpsStatusPosX )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewGpsStatusPosX, offsetof( OnScreenDisplayPageSettings2Data, GpsStatusPosX), sizeof(int16_t));
}
void OnScreenDisplayPageSettings2GpsStatusPosXGet( int16_t *NewGpsStatusPosX )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewGpsStatusPosX, offsetof( OnScreenDisplayPageSettings2Data, GpsStatusPosX), sizeof(int16_t));
}
void OnScreenDisplayPageSettings2GpsStatusPosYSet( int16_t *NewGpsStatusPosY )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewGpsStatusPosY, offsetof( OnScreenDisplayPageSettings2Data, GpsStatusPosY), sizeof(int16_t));
}
void OnScreenDisplayPageSettings2GpsStatusPosYGet( int16_t *NewGpsStatusPosY )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewGpsStatusPosY, offsetof( OnScreenDisplayPageSettings2Data, GpsStatusPosY), sizeof(int16_t));
}
void OnScreenDisplayPageSettings2GpsLatPosXSet( int16_t *NewGpsLatPosX )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewGpsLatPosX, offsetof( OnScreenDisplayPageSettings2Data, GpsLatPosX), sizeof(int16_t));
}
void OnScreenDisplayPageSettings2GpsLatPosXGet( int16_t *NewGpsLatPosX )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewGpsLatPosX, offsetof( OnScreenDisplayPageSettings2Data, GpsLatPosX), sizeof(int16_t));
}
void OnScreenDisplayPageSettings2GpsLatPosYSet( int16_t *NewGpsLatPosY )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewGpsLatPosY, offsetof( OnScreenDisplayPageSettings2Data, GpsLatPosY), sizeof(int16_t));
}
void OnScreenDisplayPageSettings2GpsLatPosYGet( int16_t *NewGpsLatPosY )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewGpsLatPosY, offsetof( OnScreenDisplayPageSettings2Data, GpsLatPosY), sizeof(int16_t));
}
void OnScreenDisplayPageSettings2GpsLonPosXSet( int16_t *NewGpsLonPosX )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewGpsLonPosX, offsetof( OnScreenDisplayPageSettings2Data, GpsLonPosX), sizeof(int16_t));
}
void OnScreenDisplayPageSettings2GpsLonPosXGet( int16_t *NewGpsLonPosX )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewGpsLonPosX, offsetof( OnScreenDisplayPageSettings2Data, GpsLonPosX), sizeof(int16_t));
}
void OnScreenDisplayPageSettings2GpsLonPosYSet( int16_t *NewGpsLonPosY )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewGpsLonPosY, offsetof( OnScreenDisplayPageSettings2Data, GpsLonPosY), sizeof(int16_t));
}
void OnScreenDisplayPageSettings2GpsLonPosYGet( int16_t *NewGpsLonPosY )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewGpsLonPosY, offsetof( OnScreenDisplayPageSettings2Data, GpsLonPosY), sizeof(int16_t));
}
void OnScreenDisplayPageSettings2HomeDistancePosXSet( int16_t *NewHomeDistancePosX )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewHomeDistancePosX, offsetof( OnScreenDisplayPageSettings2Data, HomeDistancePosX), sizeof(int16_t));
}
void OnScreenDisplayPageSettings2HomeDistancePosXGet( int16_t *NewHomeDistancePosX )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewHomeDistancePosX, offsetof( OnScreenDisplayPageSettings2Data, HomeDistancePosX), sizeof(int16_t));
}
void OnScreenDisplayPageSettings2HomeDistancePosYSet( int16_t *NewHomeDistancePosY )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewHomeDistancePosY, offsetof( OnScreenDisplayPageSettings2Data, HomeDistancePosY), sizeof(int16_t));
}
void OnScreenDisplayPageSettings2HomeDistancePosYGet( int16_t *NewHomeDistancePosY )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewHomeDistancePosY, offsetof( OnScreenDisplayPageSettings2Data, HomeDistancePosY), sizeof(int16_t));
}
void OnScreenDisplayPageSettings2RssiPosXSet( int16_t *NewRssiPosX )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewRssiPosX, offsetof( OnScreenDisplayPageSettings2Data, RssiPosX), sizeof(int16_t));
}
void OnScreenDisplayPageSettings2RssiPosXGet( int16_t *NewRssiPosX )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewRssiPosX, offsetof( OnScreenDisplayPageSettings2Data, RssiPosX), sizeof(int16_t));
}
void OnScreenDisplayPageSettings2RssiPosYSet( int16_t *NewRssiPosY )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewRssiPosY, offsetof( OnScreenDisplayPageSettings2Data, RssiPosY), sizeof(int16_t));
}
void OnScreenDisplayPageSettings2RssiPosYGet( int16_t *NewRssiPosY )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewRssiPosY, offsetof( OnScreenDisplayPageSettings2Data, RssiPosY), sizeof(int16_t));
}
void OnScreenDisplayPageSettings2SpeedScalePosSet( int16_t *NewSpeedScalePos )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewSpeedScalePos, offsetof( OnScreenDisplayPageSettings2Data, SpeedScalePos), sizeof(int16_t));
}
void OnScreenDisplayPageSettings2SpeedScalePosGet( int16_t *NewSpeedScalePos )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewSpeedScalePos, offsetof( OnScreenDisplayPageSettings2Data, SpeedScalePos), sizeof(int16_t));
}
void OnScreenDisplayPageSettings2TimePosXSet( int16_t *NewTimePosX )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewTimePosX, offsetof( OnScreenDisplayPageSettings2Data, TimePosX), sizeof(int16_t));
}
void OnScreenDisplayPageSettings2TimePosXGet( int16_t *NewTimePosX )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewTimePosX, offsetof( OnScreenDisplayPageSettings2Data, TimePosX), sizeof(int16_t));
}
void OnScreenDisplayPageSettings2TimePosYSet( int16_t *NewTimePosY )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewTimePosY, offsetof( OnScreenDisplayPageSettings2Data, TimePosY), sizeof(int16_t));
}
void OnScreenDisplayPageSettings2TimePosYGet( int16_t *NewTimePosY )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewTimePosY, offsetof( OnScreenDisplayPageSettings2Data, TimePosY), sizeof(int16_t));
}
void OnScreenDisplayPageSettings2AlarmSet( uint8_t *NewAlarm )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewAlarm, offsetof( OnScreenDisplayPageSettings2Data, Alarm), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2AlarmGet( uint8_t *NewAlarm )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewAlarm, offsetof( OnScreenDisplayPageSettings2Data, Alarm), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2AlarmFontSet( uint8_t *NewAlarmFont )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewAlarmFont, offsetof( OnScreenDisplayPageSettings2Data, AlarmFont), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2AlarmFontGet( uint8_t *NewAlarmFont )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewAlarmFont, offsetof( OnScreenDisplayPageSettings2Data, AlarmFont), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2AlarmAlignSet( uint8_t *NewAlarmAlign )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewAlarmAlign, offsetof( OnScreenDisplayPageSettings2Data, AlarmAlign), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2AlarmAlignGet( uint8_t *NewAlarmAlign )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewAlarmAlign, offsetof( OnScreenDisplayPageSettings2Data, AlarmAlign), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2AltitudeScaleSet( uint8_t *NewAltitudeScale )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewAltitudeScale, offsetof( OnScreenDisplayPageSettings2Data, AltitudeScale), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2AltitudeScaleGet( uint8_t *NewAltitudeScale )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewAltitudeScale, offsetof( OnScreenDisplayPageSettings2Data, AltitudeScale), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2AltitudeScaleAlignSet( uint8_t *NewAltitudeScaleAlign )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewAltitudeScaleAlign, offsetof( OnScreenDisplayPageSettings2Data, AltitudeScaleAlign), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2AltitudeScaleAlignGet( uint8_t *NewAltitudeScaleAlign )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewAltitudeScaleAlign, offsetof( OnScreenDisplayPageSettings2Data, AltitudeScaleAlign), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2AltitudeScaleSourceSet( uint8_t *NewAltitudeScaleSource )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewAltitudeScaleSource, offsetof( OnScreenDisplayPageSettings2Data, AltitudeScaleSource), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2AltitudeScaleSourceGet( uint8_t *NewAltitudeScaleSource )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewAltitudeScaleSource, offsetof( OnScreenDisplayPageSettings2Data, AltitudeScaleSource), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2ArmStatusSet( uint8_t *NewArmStatus )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewArmStatus, offsetof( OnScreenDisplayPageSettings2Data, ArmStatus), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2ArmStatusGet( uint8_t *NewArmStatus )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewArmStatus, offsetof( OnScreenDisplayPageSettings2Data, ArmStatus), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2ArmStatusFontSet( uint8_t *NewArmStatusFont )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewArmStatusFont, offsetof( OnScreenDisplayPageSettings2Data, ArmStatusFont), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2ArmStatusFontGet( uint8_t *NewArmStatusFont )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewArmStatusFont, offsetof( OnScreenDisplayPageSettings2Data, ArmStatusFont), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2ArmStatusAlignSet( uint8_t *NewArmStatusAlign )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewArmStatusAlign, offsetof( OnScreenDisplayPageSettings2Data, ArmStatusAlign), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2ArmStatusAlignGet( uint8_t *NewArmStatusAlign )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewArmStatusAlign, offsetof( OnScreenDisplayPageSettings2Data, ArmStatusAlign), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2ArtificialHorizonSet( uint8_t *NewArtificialHorizon )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewArtificialHorizon, offsetof( OnScreenDisplayPageSettings2Data, ArtificialHorizon), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2ArtificialHorizonGet( uint8_t *NewArtificialHorizon )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewArtificialHorizon, offsetof( OnScreenDisplayPageSettings2Data, ArtificialHorizon), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2BatteryVoltSet( uint8_t *NewBatteryVolt )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewBatteryVolt, offsetof( OnScreenDisplayPageSettings2Data, BatteryVolt), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2BatteryVoltGet( uint8_t *NewBatteryVolt )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewBatteryVolt, offsetof( OnScreenDisplayPageSettings2Data, BatteryVolt), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2BatteryVoltFontSet( uint8_t *NewBatteryVoltFont )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewBatteryVoltFont, offsetof( OnScreenDisplayPageSettings2Data, BatteryVoltFont), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2BatteryVoltFontGet( uint8_t *NewBatteryVoltFont )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewBatteryVoltFont, offsetof( OnScreenDisplayPageSettings2Data, BatteryVoltFont), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2BatteryVoltAlignSet( uint8_t *NewBatteryVoltAlign )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewBatteryVoltAlign, offsetof( OnScreenDisplayPageSettings2Data, BatteryVoltAlign), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2BatteryVoltAlignGet( uint8_t *NewBatteryVoltAlign )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewBatteryVoltAlign, offsetof( OnScreenDisplayPageSettings2Data, BatteryVoltAlign), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2BatteryCurrentSet( uint8_t *NewBatteryCurrent )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewBatteryCurrent, offsetof( OnScreenDisplayPageSettings2Data, BatteryCurrent), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2BatteryCurrentGet( uint8_t *NewBatteryCurrent )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewBatteryCurrent, offsetof( OnScreenDisplayPageSettings2Data, BatteryCurrent), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2BatteryCurrentFontSet( uint8_t *NewBatteryCurrentFont )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewBatteryCurrentFont, offsetof( OnScreenDisplayPageSettings2Data, BatteryCurrentFont), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2BatteryCurrentFontGet( uint8_t *NewBatteryCurrentFont )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewBatteryCurrentFont, offsetof( OnScreenDisplayPageSettings2Data, BatteryCurrentFont), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2BatteryCurrentAlignSet( uint8_t *NewBatteryCurrentAlign )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewBatteryCurrentAlign, offsetof( OnScreenDisplayPageSettings2Data, BatteryCurrentAlign), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2BatteryCurrentAlignGet( uint8_t *NewBatteryCurrentAlign )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewBatteryCurrentAlign, offsetof( OnScreenDisplayPageSettings2Data, BatteryCurrentAlign), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2BatteryConsumedSet( uint8_t *NewBatteryConsumed )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewBatteryConsumed, offsetof( OnScreenDisplayPageSettings2Data, BatteryConsumed), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2BatteryConsumedGet( uint8_t *NewBatteryConsumed )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewBatteryConsumed, offsetof( OnScreenDisplayPageSettings2Data, BatteryConsumed), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2BatteryConsumedFontSet( uint8_t *NewBatteryConsumedFont )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewBatteryConsumedFont, offsetof( OnScreenDisplayPageSettings2Data, BatteryConsumedFont), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2BatteryConsumedFontGet( uint8_t *NewBatteryConsumedFont )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewBatteryConsumedFont, offsetof( OnScreenDisplayPageSettings2Data, BatteryConsumedFont), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2BatteryConsumedAlignSet( uint8_t *NewBatteryConsumedAlign )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewBatteryConsumedAlign, offsetof( OnScreenDisplayPageSettings2Data, BatteryConsumedAlign), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2BatteryConsumedAlignGet( uint8_t *NewBatteryConsumedAlign )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewBatteryConsumedAlign, offsetof( OnScreenDisplayPageSettings2Data, BatteryConsumedAlign), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2CompassSet( uint8_t *NewCompass )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewCompass, offsetof( OnScreenDisplayPageSettings2Data, Compass), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2CompassGet( uint8_t *NewCompass )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewCompass, offsetof( OnScreenDisplayPageSettings2Data, Compass), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2CompassHomeDirSet( uint8_t *NewCompassHomeDir )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewCompassHomeDir, offsetof( OnScreenDisplayPageSettings2Data, CompassHomeDir), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2CompassHomeDirGet( uint8_t *NewCompassHomeDir )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewCompassHomeDir, offsetof( OnScreenDisplayPageSettings2Data, CompassHomeDir), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2CpuSet( uint8_t *NewCpu )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewCpu, offsetof( OnScreenDisplayPageSettings2Data, Cpu), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2CpuGet( uint8_t *NewCpu )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewCpu, offsetof( OnScreenDisplayPageSettings2Data, Cpu), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2CpuFontSet( uint8_t *NewCpuFont )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewCpuFont, offsetof( OnScreenDisplayPageSettings2Data, CpuFont), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2CpuFontGet( uint8_t *NewCpuFont )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewCpuFont, offsetof( OnScreenDisplayPageSettings2Data, CpuFont), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2CpuAlignSet( uint8_t *NewCpuAlign )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewCpuAlign, offsetof( OnScreenDisplayPageSettings2Data, CpuAlign), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2CpuAlignGet( uint8_t *NewCpuAlign )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewCpuAlign, offsetof( OnScreenDisplayPageSettings2Data, CpuAlign), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2FlightModeSet( uint8_t *NewFlightMode )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewFlightMode, offsetof( OnScreenDisplayPageSettings2Data, FlightMode), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2FlightModeGet( uint8_t *NewFlightMode )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewFlightMode, offsetof( OnScreenDisplayPageSettings2Data, FlightMode), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2FlightModeFontSet( uint8_t *NewFlightModeFont )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewFlightModeFont, offsetof( OnScreenDisplayPageSettings2Data, FlightModeFont), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2FlightModeFontGet( uint8_t *NewFlightModeFont )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewFlightModeFont, offsetof( OnScreenDisplayPageSettings2Data, FlightModeFont), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2FlightModeAlignSet( uint8_t *NewFlightModeAlign )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewFlightModeAlign, offsetof( OnScreenDisplayPageSettings2Data, FlightModeAlign), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2FlightModeAlignGet( uint8_t *NewFlightModeAlign )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewFlightModeAlign, offsetof( OnScreenDisplayPageSettings2Data, FlightModeAlign), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2GpsStatusSet( uint8_t *NewGpsStatus )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewGpsStatus, offsetof( OnScreenDisplayPageSettings2Data, GpsStatus), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2GpsStatusGet( uint8_t *NewGpsStatus )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewGpsStatus, offsetof( OnScreenDisplayPageSettings2Data, GpsStatus), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2GpsStatusFontSet( uint8_t *NewGpsStatusFont )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewGpsStatusFont, offsetof( OnScreenDisplayPageSettings2Data, GpsStatusFont), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2GpsStatusFontGet( uint8_t *NewGpsStatusFont )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewGpsStatusFont, offsetof( OnScreenDisplayPageSettings2Data, GpsStatusFont), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2GpsStatusAlignSet( uint8_t *NewGpsStatusAlign )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewGpsStatusAlign, offsetof( OnScreenDisplayPageSettings2Data, GpsStatusAlign), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2GpsStatusAlignGet( uint8_t *NewGpsStatusAlign )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewGpsStatusAlign, offsetof( OnScreenDisplayPageSettings2Data, GpsStatusAlign), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2GpsLatSet( uint8_t *NewGpsLat )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewGpsLat, offsetof( OnScreenDisplayPageSettings2Data, GpsLat), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2GpsLatGet( uint8_t *NewGpsLat )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewGpsLat, offsetof( OnScreenDisplayPageSettings2Data, GpsLat), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2GpsLatFontSet( uint8_t *NewGpsLatFont )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewGpsLatFont, offsetof( OnScreenDisplayPageSettings2Data, GpsLatFont), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2GpsLatFontGet( uint8_t *NewGpsLatFont )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewGpsLatFont, offsetof( OnScreenDisplayPageSettings2Data, GpsLatFont), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2GpsLatAlignSet( uint8_t *NewGpsLatAlign )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewGpsLatAlign, offsetof( OnScreenDisplayPageSettings2Data, GpsLatAlign), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2GpsLatAlignGet( uint8_t *NewGpsLatAlign )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewGpsLatAlign, offsetof( OnScreenDisplayPageSettings2Data, GpsLatAlign), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2GpsLonSet( uint8_t *NewGpsLon )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewGpsLon, offsetof( OnScreenDisplayPageSettings2Data, GpsLon), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2GpsLonGet( uint8_t *NewGpsLon )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewGpsLon, offsetof( OnScreenDisplayPageSettings2Data, GpsLon), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2GpsLonFontSet( uint8_t *NewGpsLonFont )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewGpsLonFont, offsetof( OnScreenDisplayPageSettings2Data, GpsLonFont), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2GpsLonFontGet( uint8_t *NewGpsLonFont )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewGpsLonFont, offsetof( OnScreenDisplayPageSettings2Data, GpsLonFont), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2GpsLonAlignSet( uint8_t *NewGpsLonAlign )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewGpsLonAlign, offsetof( OnScreenDisplayPageSettings2Data, GpsLonAlign), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2GpsLonAlignGet( uint8_t *NewGpsLonAlign )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewGpsLonAlign, offsetof( OnScreenDisplayPageSettings2Data, GpsLonAlign), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2HomeDistanceSet( uint8_t *NewHomeDistance )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewHomeDistance, offsetof( OnScreenDisplayPageSettings2Data, HomeDistance), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2HomeDistanceGet( uint8_t *NewHomeDistance )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewHomeDistance, offsetof( OnScreenDisplayPageSettings2Data, HomeDistance), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2HomeDistanceFontSet( uint8_t *NewHomeDistanceFont )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewHomeDistanceFont, offsetof( OnScreenDisplayPageSettings2Data, HomeDistanceFont), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2HomeDistanceFontGet( uint8_t *NewHomeDistanceFont )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewHomeDistanceFont, offsetof( OnScreenDisplayPageSettings2Data, HomeDistanceFont), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2HomeDistanceAlignSet( uint8_t *NewHomeDistanceAlign )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewHomeDistanceAlign, offsetof( OnScreenDisplayPageSettings2Data, HomeDistanceAlign), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2HomeDistanceAlignGet( uint8_t *NewHomeDistanceAlign )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewHomeDistanceAlign, offsetof( OnScreenDisplayPageSettings2Data, HomeDistanceAlign), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2RssiSet( uint8_t *NewRssi )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewRssi, offsetof( OnScreenDisplayPageSettings2Data, Rssi), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2RssiGet( uint8_t *NewRssi )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewRssi, offsetof( OnScreenDisplayPageSettings2Data, Rssi), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2RssiFontSet( uint8_t *NewRssiFont )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewRssiFont, offsetof( OnScreenDisplayPageSettings2Data, RssiFont), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2RssiFontGet( uint8_t *NewRssiFont )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewRssiFont, offsetof( OnScreenDisplayPageSettings2Data, RssiFont), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2RssiAlignSet( uint8_t *NewRssiAlign )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewRssiAlign, offsetof( OnScreenDisplayPageSettings2Data, RssiAlign), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2RssiAlignGet( uint8_t *NewRssiAlign )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewRssiAlign, offsetof( OnScreenDisplayPageSettings2Data, RssiAlign), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2SpeedScaleSet( uint8_t *NewSpeedScale )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewSpeedScale, offsetof( OnScreenDisplayPageSettings2Data, SpeedScale), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2SpeedScaleGet( uint8_t *NewSpeedScale )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewSpeedScale, offsetof( OnScreenDisplayPageSettings2Data, SpeedScale), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2SpeedScaleAlignSet( uint8_t *NewSpeedScaleAlign )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewSpeedScaleAlign, offsetof( OnScreenDisplayPageSettings2Data, SpeedScaleAlign), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2SpeedScaleAlignGet( uint8_t *NewSpeedScaleAlign )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewSpeedScaleAlign, offsetof( OnScreenDisplayPageSettings2Data, SpeedScaleAlign), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2SpeedScaleSourceSet( uint8_t *NewSpeedScaleSource )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewSpeedScaleSource, offsetof( OnScreenDisplayPageSettings2Data, SpeedScaleSource), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2SpeedScaleSourceGet( uint8_t *NewSpeedScaleSource )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewSpeedScaleSource, offsetof( OnScreenDisplayPageSettings2Data, SpeedScaleSource), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2TimeSet( uint8_t *NewTime )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewTime, offsetof( OnScreenDisplayPageSettings2Data, Time), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2TimeGet( uint8_t *NewTime )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewTime, offsetof( OnScreenDisplayPageSettings2Data, Time), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2TimeFontSet( uint8_t *NewTimeFont )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewTimeFont, offsetof( OnScreenDisplayPageSettings2Data, TimeFont), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2TimeFontGet( uint8_t *NewTimeFont )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewTimeFont, offsetof( OnScreenDisplayPageSettings2Data, TimeFont), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2TimeAlignSet( uint8_t *NewTimeAlign )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewTimeAlign, offsetof( OnScreenDisplayPageSettings2Data, TimeAlign), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings2TimeAlignGet( uint8_t *NewTimeAlign )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings2Handle(), (void*)NewTimeAlign, offsetof( OnScreenDisplayPageSettings2Data, TimeAlign), sizeof(uint8_t));
}


/**
 * @}
 * @}
 */

