/**
 ******************************************************************************
 * @addtogroup TauLabsCore Tau Labs Core components
 * @{
 * @addtogroup UAVObjects UAVObject set for this firmware
 * @{
 *
 * @file       onscreendisplaypagesettings3.c
 * @author     The OpenPilot Team, http://www.openpilot.org Copyright (C) 2010.
 * @author     Tau Labs, http://taulabs.org, Copyright (C) 2012-2013
 * @brief      Implementation of the OnScreenDisplayPageSettings3 object. This file has been 
 *             automatically generated by the UAVObjectGenerator.
 * 
 * @note       Object definition file: onscreendisplaypagesettings3.xml. 
 *             This is an automatically generated file.
 *             DO NOT modify manually.
 *
 * @see        The GNU Public License (GPL) Version 3
 *
 *****************************************************************************/
/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */

#include "openpilot.h"
#include "onscreendisplaypagesettings3.h"

// Private variables
static UAVObjHandle handle = NULL;

/**
 * Initialize object.
 * \return 0 Success
 * \return -1 Failure to initialize or -2 for already initialized
 */
int32_t OnScreenDisplayPageSettings3Initialize(void)
{
	// Don't set the handle to null if already registered
	if(UAVObjGetByID(ONSCREENDISPLAYPAGESETTINGS3_OBJID) != NULL)
		return -2;
	
	// Register object with the object manager
	handle = UAVObjRegister(ONSCREENDISPLAYPAGESETTINGS3_OBJID,
			ONSCREENDISPLAYPAGESETTINGS3_ISSINGLEINST, ONSCREENDISPLAYPAGESETTINGS3_ISSETTINGS, ONSCREENDISPLAYPAGESETTINGS3_NUMBYTES, &OnScreenDisplayPageSettings3SetDefaults);

	// Done
	if (handle != 0)
	{
		return 0;
	}
	else
	{
		return -1;
	}
}

/**
 * Initialize object fields and metadata with the default values.
 * If a default value is not specified the object fields
 * will be initialized to zero.
 */
void OnScreenDisplayPageSettings3SetDefaults(UAVObjHandle obj, uint16_t instId)
{
	OnScreenDisplayPageSettings3Data data;
	UAVObjMetadata metadata;

	// Initialize object fields to their default values
	UAVObjGetInstanceData(obj, instId, &data);
	memset(&data, 0, sizeof(OnScreenDisplayPageSettings3Data));
	data.AlarmPosX = 0;
	data.AlarmPosY = 220;
	data.AltitudeScalePos = 350;
	data.ArmStatusPosX = 0;
	data.ArmStatusPosY = 14;
	data.BatteryVoltPosX = 350;
	data.BatteryVoltPosY = 4;
	data.BatteryCurrentPosX = 350;
	data.BatteryCurrentPosY = 14;
	data.BatteryConsumedPosX = 350;
	data.BatteryConsumedPosY = 24;
	data.CompassPos = 15;
	data.CpuPosX = 0;
	data.CpuPosY = 210;
	data.FlightModePosX = 0;
	data.FlightModePosY = 4;
	data.GpsStatusPosX = 0;
	data.GpsStatusPosY = 230;
	data.GpsLatPosX = 210;
	data.GpsLatPosY = 230;
	data.GpsLonPosX = 350;
	data.GpsLonPosY = 230;
	data.HomeDistancePosX = 150;
	data.HomeDistancePosY = 210;
	data.RssiPosX = 150;
	data.RssiPosY = 195;
	data.SpeedScalePos = 0;
	data.TimePosX = 350;
	data.TimePosY = 220;
	data.Alarm = 1;
	data.AlarmFont = 0;
	data.AlarmAlign = 0;
	data.AltitudeScale = 1;
	data.AltitudeScaleAlign = 1;
	data.AltitudeScaleSource = 0;
	data.ArmStatus = 1;
	data.ArmStatusFont = 0;
	data.ArmStatusAlign = 0;
	data.ArtificialHorizon = 1;
	data.BatteryVolt = 1;
	data.BatteryVoltFont = 0;
	data.BatteryVoltAlign = 2;
	data.BatteryCurrent = 1;
	data.BatteryCurrentFont = 0;
	data.BatteryCurrentAlign = 2;
	data.BatteryConsumed = 1;
	data.BatteryConsumedFont = 0;
	data.BatteryConsumedAlign = 2;
	data.Compass = 1;
	data.CompassHomeDir = 1;
	data.Cpu = 0;
	data.CpuFont = 0;
	data.CpuAlign = 0;
	data.FlightMode = 1;
	data.FlightModeFont = 0;
	data.FlightModeAlign = 0;
	data.GpsStatus = 1;
	data.GpsStatusFont = 0;
	data.GpsStatusAlign = 0;
	data.GpsLat = 1;
	data.GpsLatFont = 0;
	data.GpsLatAlign = 0;
	data.GpsLon = 1;
	data.GpsLonFont = 0;
	data.GpsLonAlign = 2;
	data.HomeDistance = 1;
	data.HomeDistanceFont = 0;
	data.HomeDistanceAlign = 0;
	data.Rssi = 1;
	data.RssiFont = 0;
	data.RssiAlign = 0;
	data.SpeedScale = 1;
	data.SpeedScaleAlign = 0;
	data.SpeedScaleSource = 0;
	data.Time = 1;
	data.TimeFont = 0;
	data.TimeAlign = 2;

	UAVObjSetInstanceData(obj, instId, &data);

	// Initialize object metadata to their default values
	metadata.flags =
		ACCESS_READWRITE << UAVOBJ_ACCESS_SHIFT |
		ACCESS_READWRITE << UAVOBJ_GCS_ACCESS_SHIFT |
		1 << UAVOBJ_TELEMETRY_ACKED_SHIFT |
		1 << UAVOBJ_GCS_TELEMETRY_ACKED_SHIFT |
		UPDATEMODE_ONCHANGE << UAVOBJ_TELEMETRY_UPDATE_MODE_SHIFT |
		UPDATEMODE_ONCHANGE << UAVOBJ_GCS_TELEMETRY_UPDATE_MODE_SHIFT;
	metadata.telemetryUpdatePeriod = 0;
	metadata.gcsTelemetryUpdatePeriod = 0;
	metadata.loggingUpdatePeriod = 0;
	UAVObjSetMetadata(obj, &metadata);
}

/**
 * Get object handle
 */
UAVObjHandle OnScreenDisplayPageSettings3Handle()
{
	return handle;
}

/**
 * Get/Set object Functions
 */
void OnScreenDisplayPageSettings3AlarmPosXSet( int16_t *NewAlarmPosX )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewAlarmPosX, offsetof( OnScreenDisplayPageSettings3Data, AlarmPosX), sizeof(int16_t));
}
void OnScreenDisplayPageSettings3AlarmPosXGet( int16_t *NewAlarmPosX )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewAlarmPosX, offsetof( OnScreenDisplayPageSettings3Data, AlarmPosX), sizeof(int16_t));
}
void OnScreenDisplayPageSettings3AlarmPosYSet( int16_t *NewAlarmPosY )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewAlarmPosY, offsetof( OnScreenDisplayPageSettings3Data, AlarmPosY), sizeof(int16_t));
}
void OnScreenDisplayPageSettings3AlarmPosYGet( int16_t *NewAlarmPosY )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewAlarmPosY, offsetof( OnScreenDisplayPageSettings3Data, AlarmPosY), sizeof(int16_t));
}
void OnScreenDisplayPageSettings3AltitudeScalePosSet( int16_t *NewAltitudeScalePos )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewAltitudeScalePos, offsetof( OnScreenDisplayPageSettings3Data, AltitudeScalePos), sizeof(int16_t));
}
void OnScreenDisplayPageSettings3AltitudeScalePosGet( int16_t *NewAltitudeScalePos )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewAltitudeScalePos, offsetof( OnScreenDisplayPageSettings3Data, AltitudeScalePos), sizeof(int16_t));
}
void OnScreenDisplayPageSettings3ArmStatusPosXSet( int16_t *NewArmStatusPosX )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewArmStatusPosX, offsetof( OnScreenDisplayPageSettings3Data, ArmStatusPosX), sizeof(int16_t));
}
void OnScreenDisplayPageSettings3ArmStatusPosXGet( int16_t *NewArmStatusPosX )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewArmStatusPosX, offsetof( OnScreenDisplayPageSettings3Data, ArmStatusPosX), sizeof(int16_t));
}
void OnScreenDisplayPageSettings3ArmStatusPosYSet( int16_t *NewArmStatusPosY )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewArmStatusPosY, offsetof( OnScreenDisplayPageSettings3Data, ArmStatusPosY), sizeof(int16_t));
}
void OnScreenDisplayPageSettings3ArmStatusPosYGet( int16_t *NewArmStatusPosY )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewArmStatusPosY, offsetof( OnScreenDisplayPageSettings3Data, ArmStatusPosY), sizeof(int16_t));
}
void OnScreenDisplayPageSettings3BatteryVoltPosXSet( int16_t *NewBatteryVoltPosX )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewBatteryVoltPosX, offsetof( OnScreenDisplayPageSettings3Data, BatteryVoltPosX), sizeof(int16_t));
}
void OnScreenDisplayPageSettings3BatteryVoltPosXGet( int16_t *NewBatteryVoltPosX )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewBatteryVoltPosX, offsetof( OnScreenDisplayPageSettings3Data, BatteryVoltPosX), sizeof(int16_t));
}
void OnScreenDisplayPageSettings3BatteryVoltPosYSet( int16_t *NewBatteryVoltPosY )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewBatteryVoltPosY, offsetof( OnScreenDisplayPageSettings3Data, BatteryVoltPosY), sizeof(int16_t));
}
void OnScreenDisplayPageSettings3BatteryVoltPosYGet( int16_t *NewBatteryVoltPosY )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewBatteryVoltPosY, offsetof( OnScreenDisplayPageSettings3Data, BatteryVoltPosY), sizeof(int16_t));
}
void OnScreenDisplayPageSettings3BatteryCurrentPosXSet( int16_t *NewBatteryCurrentPosX )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewBatteryCurrentPosX, offsetof( OnScreenDisplayPageSettings3Data, BatteryCurrentPosX), sizeof(int16_t));
}
void OnScreenDisplayPageSettings3BatteryCurrentPosXGet( int16_t *NewBatteryCurrentPosX )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewBatteryCurrentPosX, offsetof( OnScreenDisplayPageSettings3Data, BatteryCurrentPosX), sizeof(int16_t));
}
void OnScreenDisplayPageSettings3BatteryCurrentPosYSet( int16_t *NewBatteryCurrentPosY )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewBatteryCurrentPosY, offsetof( OnScreenDisplayPageSettings3Data, BatteryCurrentPosY), sizeof(int16_t));
}
void OnScreenDisplayPageSettings3BatteryCurrentPosYGet( int16_t *NewBatteryCurrentPosY )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewBatteryCurrentPosY, offsetof( OnScreenDisplayPageSettings3Data, BatteryCurrentPosY), sizeof(int16_t));
}
void OnScreenDisplayPageSettings3BatteryConsumedPosXSet( int16_t *NewBatteryConsumedPosX )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewBatteryConsumedPosX, offsetof( OnScreenDisplayPageSettings3Data, BatteryConsumedPosX), sizeof(int16_t));
}
void OnScreenDisplayPageSettings3BatteryConsumedPosXGet( int16_t *NewBatteryConsumedPosX )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewBatteryConsumedPosX, offsetof( OnScreenDisplayPageSettings3Data, BatteryConsumedPosX), sizeof(int16_t));
}
void OnScreenDisplayPageSettings3BatteryConsumedPosYSet( int16_t *NewBatteryConsumedPosY )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewBatteryConsumedPosY, offsetof( OnScreenDisplayPageSettings3Data, BatteryConsumedPosY), sizeof(int16_t));
}
void OnScreenDisplayPageSettings3BatteryConsumedPosYGet( int16_t *NewBatteryConsumedPosY )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewBatteryConsumedPosY, offsetof( OnScreenDisplayPageSettings3Data, BatteryConsumedPosY), sizeof(int16_t));
}
void OnScreenDisplayPageSettings3CompassPosSet( int16_t *NewCompassPos )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewCompassPos, offsetof( OnScreenDisplayPageSettings3Data, CompassPos), sizeof(int16_t));
}
void OnScreenDisplayPageSettings3CompassPosGet( int16_t *NewCompassPos )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewCompassPos, offsetof( OnScreenDisplayPageSettings3Data, CompassPos), sizeof(int16_t));
}
void OnScreenDisplayPageSettings3CpuPosXSet( int16_t *NewCpuPosX )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewCpuPosX, offsetof( OnScreenDisplayPageSettings3Data, CpuPosX), sizeof(int16_t));
}
void OnScreenDisplayPageSettings3CpuPosXGet( int16_t *NewCpuPosX )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewCpuPosX, offsetof( OnScreenDisplayPageSettings3Data, CpuPosX), sizeof(int16_t));
}
void OnScreenDisplayPageSettings3CpuPosYSet( int16_t *NewCpuPosY )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewCpuPosY, offsetof( OnScreenDisplayPageSettings3Data, CpuPosY), sizeof(int16_t));
}
void OnScreenDisplayPageSettings3CpuPosYGet( int16_t *NewCpuPosY )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewCpuPosY, offsetof( OnScreenDisplayPageSettings3Data, CpuPosY), sizeof(int16_t));
}
void OnScreenDisplayPageSettings3FlightModePosXSet( int16_t *NewFlightModePosX )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewFlightModePosX, offsetof( OnScreenDisplayPageSettings3Data, FlightModePosX), sizeof(int16_t));
}
void OnScreenDisplayPageSettings3FlightModePosXGet( int16_t *NewFlightModePosX )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewFlightModePosX, offsetof( OnScreenDisplayPageSettings3Data, FlightModePosX), sizeof(int16_t));
}
void OnScreenDisplayPageSettings3FlightModePosYSet( int16_t *NewFlightModePosY )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewFlightModePosY, offsetof( OnScreenDisplayPageSettings3Data, FlightModePosY), sizeof(int16_t));
}
void OnScreenDisplayPageSettings3FlightModePosYGet( int16_t *NewFlightModePosY )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewFlightModePosY, offsetof( OnScreenDisplayPageSettings3Data, FlightModePosY), sizeof(int16_t));
}
void OnScreenDisplayPageSettings3GpsStatusPosXSet( int16_t *NewGpsStatusPosX )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewGpsStatusPosX, offsetof( OnScreenDisplayPageSettings3Data, GpsStatusPosX), sizeof(int16_t));
}
void OnScreenDisplayPageSettings3GpsStatusPosXGet( int16_t *NewGpsStatusPosX )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewGpsStatusPosX, offsetof( OnScreenDisplayPageSettings3Data, GpsStatusPosX), sizeof(int16_t));
}
void OnScreenDisplayPageSettings3GpsStatusPosYSet( int16_t *NewGpsStatusPosY )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewGpsStatusPosY, offsetof( OnScreenDisplayPageSettings3Data, GpsStatusPosY), sizeof(int16_t));
}
void OnScreenDisplayPageSettings3GpsStatusPosYGet( int16_t *NewGpsStatusPosY )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewGpsStatusPosY, offsetof( OnScreenDisplayPageSettings3Data, GpsStatusPosY), sizeof(int16_t));
}
void OnScreenDisplayPageSettings3GpsLatPosXSet( int16_t *NewGpsLatPosX )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewGpsLatPosX, offsetof( OnScreenDisplayPageSettings3Data, GpsLatPosX), sizeof(int16_t));
}
void OnScreenDisplayPageSettings3GpsLatPosXGet( int16_t *NewGpsLatPosX )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewGpsLatPosX, offsetof( OnScreenDisplayPageSettings3Data, GpsLatPosX), sizeof(int16_t));
}
void OnScreenDisplayPageSettings3GpsLatPosYSet( int16_t *NewGpsLatPosY )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewGpsLatPosY, offsetof( OnScreenDisplayPageSettings3Data, GpsLatPosY), sizeof(int16_t));
}
void OnScreenDisplayPageSettings3GpsLatPosYGet( int16_t *NewGpsLatPosY )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewGpsLatPosY, offsetof( OnScreenDisplayPageSettings3Data, GpsLatPosY), sizeof(int16_t));
}
void OnScreenDisplayPageSettings3GpsLonPosXSet( int16_t *NewGpsLonPosX )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewGpsLonPosX, offsetof( OnScreenDisplayPageSettings3Data, GpsLonPosX), sizeof(int16_t));
}
void OnScreenDisplayPageSettings3GpsLonPosXGet( int16_t *NewGpsLonPosX )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewGpsLonPosX, offsetof( OnScreenDisplayPageSettings3Data, GpsLonPosX), sizeof(int16_t));
}
void OnScreenDisplayPageSettings3GpsLonPosYSet( int16_t *NewGpsLonPosY )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewGpsLonPosY, offsetof( OnScreenDisplayPageSettings3Data, GpsLonPosY), sizeof(int16_t));
}
void OnScreenDisplayPageSettings3GpsLonPosYGet( int16_t *NewGpsLonPosY )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewGpsLonPosY, offsetof( OnScreenDisplayPageSettings3Data, GpsLonPosY), sizeof(int16_t));
}
void OnScreenDisplayPageSettings3HomeDistancePosXSet( int16_t *NewHomeDistancePosX )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewHomeDistancePosX, offsetof( OnScreenDisplayPageSettings3Data, HomeDistancePosX), sizeof(int16_t));
}
void OnScreenDisplayPageSettings3HomeDistancePosXGet( int16_t *NewHomeDistancePosX )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewHomeDistancePosX, offsetof( OnScreenDisplayPageSettings3Data, HomeDistancePosX), sizeof(int16_t));
}
void OnScreenDisplayPageSettings3HomeDistancePosYSet( int16_t *NewHomeDistancePosY )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewHomeDistancePosY, offsetof( OnScreenDisplayPageSettings3Data, HomeDistancePosY), sizeof(int16_t));
}
void OnScreenDisplayPageSettings3HomeDistancePosYGet( int16_t *NewHomeDistancePosY )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewHomeDistancePosY, offsetof( OnScreenDisplayPageSettings3Data, HomeDistancePosY), sizeof(int16_t));
}
void OnScreenDisplayPageSettings3RssiPosXSet( int16_t *NewRssiPosX )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewRssiPosX, offsetof( OnScreenDisplayPageSettings3Data, RssiPosX), sizeof(int16_t));
}
void OnScreenDisplayPageSettings3RssiPosXGet( int16_t *NewRssiPosX )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewRssiPosX, offsetof( OnScreenDisplayPageSettings3Data, RssiPosX), sizeof(int16_t));
}
void OnScreenDisplayPageSettings3RssiPosYSet( int16_t *NewRssiPosY )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewRssiPosY, offsetof( OnScreenDisplayPageSettings3Data, RssiPosY), sizeof(int16_t));
}
void OnScreenDisplayPageSettings3RssiPosYGet( int16_t *NewRssiPosY )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewRssiPosY, offsetof( OnScreenDisplayPageSettings3Data, RssiPosY), sizeof(int16_t));
}
void OnScreenDisplayPageSettings3SpeedScalePosSet( int16_t *NewSpeedScalePos )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewSpeedScalePos, offsetof( OnScreenDisplayPageSettings3Data, SpeedScalePos), sizeof(int16_t));
}
void OnScreenDisplayPageSettings3SpeedScalePosGet( int16_t *NewSpeedScalePos )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewSpeedScalePos, offsetof( OnScreenDisplayPageSettings3Data, SpeedScalePos), sizeof(int16_t));
}
void OnScreenDisplayPageSettings3TimePosXSet( int16_t *NewTimePosX )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewTimePosX, offsetof( OnScreenDisplayPageSettings3Data, TimePosX), sizeof(int16_t));
}
void OnScreenDisplayPageSettings3TimePosXGet( int16_t *NewTimePosX )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewTimePosX, offsetof( OnScreenDisplayPageSettings3Data, TimePosX), sizeof(int16_t));
}
void OnScreenDisplayPageSettings3TimePosYSet( int16_t *NewTimePosY )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewTimePosY, offsetof( OnScreenDisplayPageSettings3Data, TimePosY), sizeof(int16_t));
}
void OnScreenDisplayPageSettings3TimePosYGet( int16_t *NewTimePosY )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewTimePosY, offsetof( OnScreenDisplayPageSettings3Data, TimePosY), sizeof(int16_t));
}
void OnScreenDisplayPageSettings3AlarmSet( uint8_t *NewAlarm )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewAlarm, offsetof( OnScreenDisplayPageSettings3Data, Alarm), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3AlarmGet( uint8_t *NewAlarm )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewAlarm, offsetof( OnScreenDisplayPageSettings3Data, Alarm), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3AlarmFontSet( uint8_t *NewAlarmFont )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewAlarmFont, offsetof( OnScreenDisplayPageSettings3Data, AlarmFont), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3AlarmFontGet( uint8_t *NewAlarmFont )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewAlarmFont, offsetof( OnScreenDisplayPageSettings3Data, AlarmFont), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3AlarmAlignSet( uint8_t *NewAlarmAlign )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewAlarmAlign, offsetof( OnScreenDisplayPageSettings3Data, AlarmAlign), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3AlarmAlignGet( uint8_t *NewAlarmAlign )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewAlarmAlign, offsetof( OnScreenDisplayPageSettings3Data, AlarmAlign), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3AltitudeScaleSet( uint8_t *NewAltitudeScale )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewAltitudeScale, offsetof( OnScreenDisplayPageSettings3Data, AltitudeScale), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3AltitudeScaleGet( uint8_t *NewAltitudeScale )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewAltitudeScale, offsetof( OnScreenDisplayPageSettings3Data, AltitudeScale), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3AltitudeScaleAlignSet( uint8_t *NewAltitudeScaleAlign )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewAltitudeScaleAlign, offsetof( OnScreenDisplayPageSettings3Data, AltitudeScaleAlign), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3AltitudeScaleAlignGet( uint8_t *NewAltitudeScaleAlign )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewAltitudeScaleAlign, offsetof( OnScreenDisplayPageSettings3Data, AltitudeScaleAlign), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3AltitudeScaleSourceSet( uint8_t *NewAltitudeScaleSource )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewAltitudeScaleSource, offsetof( OnScreenDisplayPageSettings3Data, AltitudeScaleSource), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3AltitudeScaleSourceGet( uint8_t *NewAltitudeScaleSource )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewAltitudeScaleSource, offsetof( OnScreenDisplayPageSettings3Data, AltitudeScaleSource), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3ArmStatusSet( uint8_t *NewArmStatus )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewArmStatus, offsetof( OnScreenDisplayPageSettings3Data, ArmStatus), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3ArmStatusGet( uint8_t *NewArmStatus )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewArmStatus, offsetof( OnScreenDisplayPageSettings3Data, ArmStatus), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3ArmStatusFontSet( uint8_t *NewArmStatusFont )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewArmStatusFont, offsetof( OnScreenDisplayPageSettings3Data, ArmStatusFont), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3ArmStatusFontGet( uint8_t *NewArmStatusFont )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewArmStatusFont, offsetof( OnScreenDisplayPageSettings3Data, ArmStatusFont), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3ArmStatusAlignSet( uint8_t *NewArmStatusAlign )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewArmStatusAlign, offsetof( OnScreenDisplayPageSettings3Data, ArmStatusAlign), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3ArmStatusAlignGet( uint8_t *NewArmStatusAlign )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewArmStatusAlign, offsetof( OnScreenDisplayPageSettings3Data, ArmStatusAlign), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3ArtificialHorizonSet( uint8_t *NewArtificialHorizon )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewArtificialHorizon, offsetof( OnScreenDisplayPageSettings3Data, ArtificialHorizon), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3ArtificialHorizonGet( uint8_t *NewArtificialHorizon )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewArtificialHorizon, offsetof( OnScreenDisplayPageSettings3Data, ArtificialHorizon), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3BatteryVoltSet( uint8_t *NewBatteryVolt )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewBatteryVolt, offsetof( OnScreenDisplayPageSettings3Data, BatteryVolt), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3BatteryVoltGet( uint8_t *NewBatteryVolt )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewBatteryVolt, offsetof( OnScreenDisplayPageSettings3Data, BatteryVolt), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3BatteryVoltFontSet( uint8_t *NewBatteryVoltFont )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewBatteryVoltFont, offsetof( OnScreenDisplayPageSettings3Data, BatteryVoltFont), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3BatteryVoltFontGet( uint8_t *NewBatteryVoltFont )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewBatteryVoltFont, offsetof( OnScreenDisplayPageSettings3Data, BatteryVoltFont), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3BatteryVoltAlignSet( uint8_t *NewBatteryVoltAlign )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewBatteryVoltAlign, offsetof( OnScreenDisplayPageSettings3Data, BatteryVoltAlign), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3BatteryVoltAlignGet( uint8_t *NewBatteryVoltAlign )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewBatteryVoltAlign, offsetof( OnScreenDisplayPageSettings3Data, BatteryVoltAlign), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3BatteryCurrentSet( uint8_t *NewBatteryCurrent )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewBatteryCurrent, offsetof( OnScreenDisplayPageSettings3Data, BatteryCurrent), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3BatteryCurrentGet( uint8_t *NewBatteryCurrent )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewBatteryCurrent, offsetof( OnScreenDisplayPageSettings3Data, BatteryCurrent), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3BatteryCurrentFontSet( uint8_t *NewBatteryCurrentFont )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewBatteryCurrentFont, offsetof( OnScreenDisplayPageSettings3Data, BatteryCurrentFont), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3BatteryCurrentFontGet( uint8_t *NewBatteryCurrentFont )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewBatteryCurrentFont, offsetof( OnScreenDisplayPageSettings3Data, BatteryCurrentFont), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3BatteryCurrentAlignSet( uint8_t *NewBatteryCurrentAlign )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewBatteryCurrentAlign, offsetof( OnScreenDisplayPageSettings3Data, BatteryCurrentAlign), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3BatteryCurrentAlignGet( uint8_t *NewBatteryCurrentAlign )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewBatteryCurrentAlign, offsetof( OnScreenDisplayPageSettings3Data, BatteryCurrentAlign), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3BatteryConsumedSet( uint8_t *NewBatteryConsumed )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewBatteryConsumed, offsetof( OnScreenDisplayPageSettings3Data, BatteryConsumed), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3BatteryConsumedGet( uint8_t *NewBatteryConsumed )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewBatteryConsumed, offsetof( OnScreenDisplayPageSettings3Data, BatteryConsumed), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3BatteryConsumedFontSet( uint8_t *NewBatteryConsumedFont )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewBatteryConsumedFont, offsetof( OnScreenDisplayPageSettings3Data, BatteryConsumedFont), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3BatteryConsumedFontGet( uint8_t *NewBatteryConsumedFont )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewBatteryConsumedFont, offsetof( OnScreenDisplayPageSettings3Data, BatteryConsumedFont), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3BatteryConsumedAlignSet( uint8_t *NewBatteryConsumedAlign )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewBatteryConsumedAlign, offsetof( OnScreenDisplayPageSettings3Data, BatteryConsumedAlign), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3BatteryConsumedAlignGet( uint8_t *NewBatteryConsumedAlign )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewBatteryConsumedAlign, offsetof( OnScreenDisplayPageSettings3Data, BatteryConsumedAlign), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3CompassSet( uint8_t *NewCompass )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewCompass, offsetof( OnScreenDisplayPageSettings3Data, Compass), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3CompassGet( uint8_t *NewCompass )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewCompass, offsetof( OnScreenDisplayPageSettings3Data, Compass), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3CompassHomeDirSet( uint8_t *NewCompassHomeDir )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewCompassHomeDir, offsetof( OnScreenDisplayPageSettings3Data, CompassHomeDir), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3CompassHomeDirGet( uint8_t *NewCompassHomeDir )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewCompassHomeDir, offsetof( OnScreenDisplayPageSettings3Data, CompassHomeDir), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3CpuSet( uint8_t *NewCpu )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewCpu, offsetof( OnScreenDisplayPageSettings3Data, Cpu), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3CpuGet( uint8_t *NewCpu )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewCpu, offsetof( OnScreenDisplayPageSettings3Data, Cpu), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3CpuFontSet( uint8_t *NewCpuFont )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewCpuFont, offsetof( OnScreenDisplayPageSettings3Data, CpuFont), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3CpuFontGet( uint8_t *NewCpuFont )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewCpuFont, offsetof( OnScreenDisplayPageSettings3Data, CpuFont), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3CpuAlignSet( uint8_t *NewCpuAlign )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewCpuAlign, offsetof( OnScreenDisplayPageSettings3Data, CpuAlign), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3CpuAlignGet( uint8_t *NewCpuAlign )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewCpuAlign, offsetof( OnScreenDisplayPageSettings3Data, CpuAlign), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3FlightModeSet( uint8_t *NewFlightMode )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewFlightMode, offsetof( OnScreenDisplayPageSettings3Data, FlightMode), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3FlightModeGet( uint8_t *NewFlightMode )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewFlightMode, offsetof( OnScreenDisplayPageSettings3Data, FlightMode), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3FlightModeFontSet( uint8_t *NewFlightModeFont )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewFlightModeFont, offsetof( OnScreenDisplayPageSettings3Data, FlightModeFont), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3FlightModeFontGet( uint8_t *NewFlightModeFont )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewFlightModeFont, offsetof( OnScreenDisplayPageSettings3Data, FlightModeFont), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3FlightModeAlignSet( uint8_t *NewFlightModeAlign )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewFlightModeAlign, offsetof( OnScreenDisplayPageSettings3Data, FlightModeAlign), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3FlightModeAlignGet( uint8_t *NewFlightModeAlign )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewFlightModeAlign, offsetof( OnScreenDisplayPageSettings3Data, FlightModeAlign), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3GpsStatusSet( uint8_t *NewGpsStatus )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewGpsStatus, offsetof( OnScreenDisplayPageSettings3Data, GpsStatus), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3GpsStatusGet( uint8_t *NewGpsStatus )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewGpsStatus, offsetof( OnScreenDisplayPageSettings3Data, GpsStatus), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3GpsStatusFontSet( uint8_t *NewGpsStatusFont )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewGpsStatusFont, offsetof( OnScreenDisplayPageSettings3Data, GpsStatusFont), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3GpsStatusFontGet( uint8_t *NewGpsStatusFont )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewGpsStatusFont, offsetof( OnScreenDisplayPageSettings3Data, GpsStatusFont), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3GpsStatusAlignSet( uint8_t *NewGpsStatusAlign )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewGpsStatusAlign, offsetof( OnScreenDisplayPageSettings3Data, GpsStatusAlign), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3GpsStatusAlignGet( uint8_t *NewGpsStatusAlign )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewGpsStatusAlign, offsetof( OnScreenDisplayPageSettings3Data, GpsStatusAlign), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3GpsLatSet( uint8_t *NewGpsLat )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewGpsLat, offsetof( OnScreenDisplayPageSettings3Data, GpsLat), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3GpsLatGet( uint8_t *NewGpsLat )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewGpsLat, offsetof( OnScreenDisplayPageSettings3Data, GpsLat), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3GpsLatFontSet( uint8_t *NewGpsLatFont )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewGpsLatFont, offsetof( OnScreenDisplayPageSettings3Data, GpsLatFont), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3GpsLatFontGet( uint8_t *NewGpsLatFont )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewGpsLatFont, offsetof( OnScreenDisplayPageSettings3Data, GpsLatFont), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3GpsLatAlignSet( uint8_t *NewGpsLatAlign )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewGpsLatAlign, offsetof( OnScreenDisplayPageSettings3Data, GpsLatAlign), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3GpsLatAlignGet( uint8_t *NewGpsLatAlign )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewGpsLatAlign, offsetof( OnScreenDisplayPageSettings3Data, GpsLatAlign), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3GpsLonSet( uint8_t *NewGpsLon )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewGpsLon, offsetof( OnScreenDisplayPageSettings3Data, GpsLon), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3GpsLonGet( uint8_t *NewGpsLon )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewGpsLon, offsetof( OnScreenDisplayPageSettings3Data, GpsLon), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3GpsLonFontSet( uint8_t *NewGpsLonFont )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewGpsLonFont, offsetof( OnScreenDisplayPageSettings3Data, GpsLonFont), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3GpsLonFontGet( uint8_t *NewGpsLonFont )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewGpsLonFont, offsetof( OnScreenDisplayPageSettings3Data, GpsLonFont), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3GpsLonAlignSet( uint8_t *NewGpsLonAlign )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewGpsLonAlign, offsetof( OnScreenDisplayPageSettings3Data, GpsLonAlign), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3GpsLonAlignGet( uint8_t *NewGpsLonAlign )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewGpsLonAlign, offsetof( OnScreenDisplayPageSettings3Data, GpsLonAlign), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3HomeDistanceSet( uint8_t *NewHomeDistance )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewHomeDistance, offsetof( OnScreenDisplayPageSettings3Data, HomeDistance), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3HomeDistanceGet( uint8_t *NewHomeDistance )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewHomeDistance, offsetof( OnScreenDisplayPageSettings3Data, HomeDistance), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3HomeDistanceFontSet( uint8_t *NewHomeDistanceFont )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewHomeDistanceFont, offsetof( OnScreenDisplayPageSettings3Data, HomeDistanceFont), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3HomeDistanceFontGet( uint8_t *NewHomeDistanceFont )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewHomeDistanceFont, offsetof( OnScreenDisplayPageSettings3Data, HomeDistanceFont), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3HomeDistanceAlignSet( uint8_t *NewHomeDistanceAlign )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewHomeDistanceAlign, offsetof( OnScreenDisplayPageSettings3Data, HomeDistanceAlign), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3HomeDistanceAlignGet( uint8_t *NewHomeDistanceAlign )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewHomeDistanceAlign, offsetof( OnScreenDisplayPageSettings3Data, HomeDistanceAlign), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3RssiSet( uint8_t *NewRssi )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewRssi, offsetof( OnScreenDisplayPageSettings3Data, Rssi), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3RssiGet( uint8_t *NewRssi )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewRssi, offsetof( OnScreenDisplayPageSettings3Data, Rssi), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3RssiFontSet( uint8_t *NewRssiFont )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewRssiFont, offsetof( OnScreenDisplayPageSettings3Data, RssiFont), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3RssiFontGet( uint8_t *NewRssiFont )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewRssiFont, offsetof( OnScreenDisplayPageSettings3Data, RssiFont), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3RssiAlignSet( uint8_t *NewRssiAlign )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewRssiAlign, offsetof( OnScreenDisplayPageSettings3Data, RssiAlign), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3RssiAlignGet( uint8_t *NewRssiAlign )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewRssiAlign, offsetof( OnScreenDisplayPageSettings3Data, RssiAlign), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3SpeedScaleSet( uint8_t *NewSpeedScale )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewSpeedScale, offsetof( OnScreenDisplayPageSettings3Data, SpeedScale), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3SpeedScaleGet( uint8_t *NewSpeedScale )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewSpeedScale, offsetof( OnScreenDisplayPageSettings3Data, SpeedScale), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3SpeedScaleAlignSet( uint8_t *NewSpeedScaleAlign )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewSpeedScaleAlign, offsetof( OnScreenDisplayPageSettings3Data, SpeedScaleAlign), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3SpeedScaleAlignGet( uint8_t *NewSpeedScaleAlign )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewSpeedScaleAlign, offsetof( OnScreenDisplayPageSettings3Data, SpeedScaleAlign), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3SpeedScaleSourceSet( uint8_t *NewSpeedScaleSource )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewSpeedScaleSource, offsetof( OnScreenDisplayPageSettings3Data, SpeedScaleSource), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3SpeedScaleSourceGet( uint8_t *NewSpeedScaleSource )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewSpeedScaleSource, offsetof( OnScreenDisplayPageSettings3Data, SpeedScaleSource), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3TimeSet( uint8_t *NewTime )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewTime, offsetof( OnScreenDisplayPageSettings3Data, Time), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3TimeGet( uint8_t *NewTime )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewTime, offsetof( OnScreenDisplayPageSettings3Data, Time), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3TimeFontSet( uint8_t *NewTimeFont )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewTimeFont, offsetof( OnScreenDisplayPageSettings3Data, TimeFont), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3TimeFontGet( uint8_t *NewTimeFont )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewTimeFont, offsetof( OnScreenDisplayPageSettings3Data, TimeFont), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3TimeAlignSet( uint8_t *NewTimeAlign )
{
	UAVObjSetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewTimeAlign, offsetof( OnScreenDisplayPageSettings3Data, TimeAlign), sizeof(uint8_t));
}
void OnScreenDisplayPageSettings3TimeAlignGet( uint8_t *NewTimeAlign )
{
	UAVObjGetDataField(OnScreenDisplayPageSettings3Handle(), (void*)NewTimeAlign, offsetof( OnScreenDisplayPageSettings3Data, TimeAlign), sizeof(uint8_t));
}


/**
 * @}
 * @}
 */

