/**
 ******************************************************************************
 * @addtogroup UAVObjects OpenPilot UAVObjects
 * @{ 
 * @addtogroup OPLinkSettings OPLinkSettings
 * @brief OPLink configurations options.
 *
 * Autogenerated files and functions for OPLinkSettings Object
 * @{ 
 *
 * @file       oplinksettings.c
 * @author     The OpenPilot Team, http://www.openpilot.org Copyright (C) 2010.
 * @brief      Implementation of the OPLinkSettings object. This file has been 
 *             automatically generated by the UAVObjectGenerator.
 * 
 * @note       Object definition file: oplinksettings.xml. 
 *             This is an automatically generated file.
 *             DO NOT modify manually.
 *
 * @see        The GNU Public License (GPL) Version 3
 *
 *****************************************************************************/
/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */

#include "openpilot.h"
#include "oplinksettings.h"

// Private variables
static UAVObjHandle handle = NULL;

/**
 * Initialize object.
 * \return 0 Success
 * \return -1 Failure to initialize or -2 for already initialized
 */
int32_t OPLinkSettingsInitialize(void)
{
	// Don't set the handle to null if already registered
	if(UAVObjGetByID(OPLINKSETTINGS_OBJID) != NULL)
		return -2;
	
	// Register object with the object manager
	handle = UAVObjRegister(OPLINKSETTINGS_OBJID,
			OPLINKSETTINGS_ISSINGLEINST, OPLINKSETTINGS_ISSETTINGS, OPLINKSETTINGS_NUMBYTES, &OPLinkSettingsSetDefaults);

	// Done
	if (handle != 0)
	{
		return 0;
	}
	else
	{
		return -1;
	}
}

/**
 * Initialize object fields and metadata with the default values.
 * If a default value is not specified the object fields
 * will be initialized to zero.
 */
void OPLinkSettingsSetDefaults(UAVObjHandle obj, uint16_t instId)
{
	OPLinkSettingsData data;
	UAVObjMetadata metadata;

	// Initialize object fields to their default values
	UAVObjGetInstanceData(obj, instId, &data);
	memset(&data, 0, sizeof(OPLinkSettingsData));
	data.PairID = 0;
	data.MinFrequency = 432000000;
	data.MaxFrequency = 436000000;
	data.SendTimeout = 50;
	data.Coordinator = 0;
	data.PPM = 0;
	data.UAVTalk = 0;
	data.InputConnection = 0;
	data.OutputConnection = 2;
	data.ComSpeed = 4;
	data.MaxRFPower = 7;
	data.MinPacketSize = 50;
	data.FrequencyCalibration = 127;
	data.AESKey[0] = 0;
	data.AESKey[1] = 0;
	data.AESKey[2] = 0;
	data.AESKey[3] = 0;
	data.AESKey[4] = 0;
	data.AESKey[5] = 0;
	data.AESKey[6] = 0;
	data.AESKey[7] = 0;
	data.AESKey[8] = 0;
	data.AESKey[9] = 0;
	data.AESKey[10] = 0;
	data.AESKey[11] = 0;
	data.AESKey[12] = 0;
	data.AESKey[13] = 0;
	data.AESKey[14] = 0;
	data.AESKey[15] = 0;
	data.AESKey[16] = 0;
	data.AESKey[17] = 0;
	data.AESKey[18] = 0;
	data.AESKey[19] = 0;
	data.AESKey[20] = 0;
	data.AESKey[21] = 0;
	data.AESKey[22] = 0;
	data.AESKey[23] = 0;
	data.AESKey[24] = 0;
	data.AESKey[25] = 0;
	data.AESKey[26] = 0;
	data.AESKey[27] = 0;
	data.AESKey[28] = 0;
	data.AESKey[29] = 0;
	data.AESKey[30] = 0;
	data.AESKey[31] = 0;

	UAVObjSetInstanceData(obj, instId, &data);

	// Initialize object metadata to their default values
	metadata.flags =
		ACCESS_READWRITE << UAVOBJ_ACCESS_SHIFT |
		ACCESS_READWRITE << UAVOBJ_GCS_ACCESS_SHIFT |
		1 << UAVOBJ_TELEMETRY_ACKED_SHIFT |
		1 << UAVOBJ_GCS_TELEMETRY_ACKED_SHIFT |
		UPDATEMODE_ONCHANGE << UAVOBJ_TELEMETRY_UPDATE_MODE_SHIFT |
		UPDATEMODE_ONCHANGE << UAVOBJ_GCS_TELEMETRY_UPDATE_MODE_SHIFT;
	metadata.telemetryUpdatePeriod = 0;
	metadata.gcsTelemetryUpdatePeriod = 0;
	metadata.loggingUpdatePeriod = 0;
	UAVObjSetMetadata(obj, &metadata);
}

/**
 * Get object handle
 */
UAVObjHandle OPLinkSettingsHandle()
{
	return handle;
}

/**
 * Get/Set object Functions
 */
void OPLinkSettingsPairIDSet( uint32_t *NewPairID )
{
	UAVObjSetDataField(OPLinkSettingsHandle(), (void*)NewPairID, offsetof( OPLinkSettingsData, PairID), sizeof(uint32_t));
}
void OPLinkSettingsPairIDGet( uint32_t *NewPairID )
{
	UAVObjGetDataField(OPLinkSettingsHandle(), (void*)NewPairID, offsetof( OPLinkSettingsData, PairID), sizeof(uint32_t));
}
void OPLinkSettingsMinFrequencySet( uint32_t *NewMinFrequency )
{
	UAVObjSetDataField(OPLinkSettingsHandle(), (void*)NewMinFrequency, offsetof( OPLinkSettingsData, MinFrequency), sizeof(uint32_t));
}
void OPLinkSettingsMinFrequencyGet( uint32_t *NewMinFrequency )
{
	UAVObjGetDataField(OPLinkSettingsHandle(), (void*)NewMinFrequency, offsetof( OPLinkSettingsData, MinFrequency), sizeof(uint32_t));
}
void OPLinkSettingsMaxFrequencySet( uint32_t *NewMaxFrequency )
{
	UAVObjSetDataField(OPLinkSettingsHandle(), (void*)NewMaxFrequency, offsetof( OPLinkSettingsData, MaxFrequency), sizeof(uint32_t));
}
void OPLinkSettingsMaxFrequencyGet( uint32_t *NewMaxFrequency )
{
	UAVObjGetDataField(OPLinkSettingsHandle(), (void*)NewMaxFrequency, offsetof( OPLinkSettingsData, MaxFrequency), sizeof(uint32_t));
}
void OPLinkSettingsSendTimeoutSet( uint16_t *NewSendTimeout )
{
	UAVObjSetDataField(OPLinkSettingsHandle(), (void*)NewSendTimeout, offsetof( OPLinkSettingsData, SendTimeout), sizeof(uint16_t));
}
void OPLinkSettingsSendTimeoutGet( uint16_t *NewSendTimeout )
{
	UAVObjGetDataField(OPLinkSettingsHandle(), (void*)NewSendTimeout, offsetof( OPLinkSettingsData, SendTimeout), sizeof(uint16_t));
}
void OPLinkSettingsCoordinatorSet( uint8_t *NewCoordinator )
{
	UAVObjSetDataField(OPLinkSettingsHandle(), (void*)NewCoordinator, offsetof( OPLinkSettingsData, Coordinator), sizeof(uint8_t));
}
void OPLinkSettingsCoordinatorGet( uint8_t *NewCoordinator )
{
	UAVObjGetDataField(OPLinkSettingsHandle(), (void*)NewCoordinator, offsetof( OPLinkSettingsData, Coordinator), sizeof(uint8_t));
}
void OPLinkSettingsPPMSet( uint8_t *NewPPM )
{
	UAVObjSetDataField(OPLinkSettingsHandle(), (void*)NewPPM, offsetof( OPLinkSettingsData, PPM), sizeof(uint8_t));
}
void OPLinkSettingsPPMGet( uint8_t *NewPPM )
{
	UAVObjGetDataField(OPLinkSettingsHandle(), (void*)NewPPM, offsetof( OPLinkSettingsData, PPM), sizeof(uint8_t));
}
void OPLinkSettingsUAVTalkSet( uint8_t *NewUAVTalk )
{
	UAVObjSetDataField(OPLinkSettingsHandle(), (void*)NewUAVTalk, offsetof( OPLinkSettingsData, UAVTalk), sizeof(uint8_t));
}
void OPLinkSettingsUAVTalkGet( uint8_t *NewUAVTalk )
{
	UAVObjGetDataField(OPLinkSettingsHandle(), (void*)NewUAVTalk, offsetof( OPLinkSettingsData, UAVTalk), sizeof(uint8_t));
}
void OPLinkSettingsInputConnectionSet( uint8_t *NewInputConnection )
{
	UAVObjSetDataField(OPLinkSettingsHandle(), (void*)NewInputConnection, offsetof( OPLinkSettingsData, InputConnection), sizeof(uint8_t));
}
void OPLinkSettingsInputConnectionGet( uint8_t *NewInputConnection )
{
	UAVObjGetDataField(OPLinkSettingsHandle(), (void*)NewInputConnection, offsetof( OPLinkSettingsData, InputConnection), sizeof(uint8_t));
}
void OPLinkSettingsOutputConnectionSet( uint8_t *NewOutputConnection )
{
	UAVObjSetDataField(OPLinkSettingsHandle(), (void*)NewOutputConnection, offsetof( OPLinkSettingsData, OutputConnection), sizeof(uint8_t));
}
void OPLinkSettingsOutputConnectionGet( uint8_t *NewOutputConnection )
{
	UAVObjGetDataField(OPLinkSettingsHandle(), (void*)NewOutputConnection, offsetof( OPLinkSettingsData, OutputConnection), sizeof(uint8_t));
}
void OPLinkSettingsComSpeedSet( uint8_t *NewComSpeed )
{
	UAVObjSetDataField(OPLinkSettingsHandle(), (void*)NewComSpeed, offsetof( OPLinkSettingsData, ComSpeed), sizeof(uint8_t));
}
void OPLinkSettingsComSpeedGet( uint8_t *NewComSpeed )
{
	UAVObjGetDataField(OPLinkSettingsHandle(), (void*)NewComSpeed, offsetof( OPLinkSettingsData, ComSpeed), sizeof(uint8_t));
}
void OPLinkSettingsMaxRFPowerSet( uint8_t *NewMaxRFPower )
{
	UAVObjSetDataField(OPLinkSettingsHandle(), (void*)NewMaxRFPower, offsetof( OPLinkSettingsData, MaxRFPower), sizeof(uint8_t));
}
void OPLinkSettingsMaxRFPowerGet( uint8_t *NewMaxRFPower )
{
	UAVObjGetDataField(OPLinkSettingsHandle(), (void*)NewMaxRFPower, offsetof( OPLinkSettingsData, MaxRFPower), sizeof(uint8_t));
}
void OPLinkSettingsMinPacketSizeSet( uint8_t *NewMinPacketSize )
{
	UAVObjSetDataField(OPLinkSettingsHandle(), (void*)NewMinPacketSize, offsetof( OPLinkSettingsData, MinPacketSize), sizeof(uint8_t));
}
void OPLinkSettingsMinPacketSizeGet( uint8_t *NewMinPacketSize )
{
	UAVObjGetDataField(OPLinkSettingsHandle(), (void*)NewMinPacketSize, offsetof( OPLinkSettingsData, MinPacketSize), sizeof(uint8_t));
}
void OPLinkSettingsFrequencyCalibrationSet( uint8_t *NewFrequencyCalibration )
{
	UAVObjSetDataField(OPLinkSettingsHandle(), (void*)NewFrequencyCalibration, offsetof( OPLinkSettingsData, FrequencyCalibration), sizeof(uint8_t));
}
void OPLinkSettingsFrequencyCalibrationGet( uint8_t *NewFrequencyCalibration )
{
	UAVObjGetDataField(OPLinkSettingsHandle(), (void*)NewFrequencyCalibration, offsetof( OPLinkSettingsData, FrequencyCalibration), sizeof(uint8_t));
}
void OPLinkSettingsAESKeySet( uint8_t *NewAESKey )
{
	UAVObjSetDataField(OPLinkSettingsHandle(), (void*)NewAESKey, offsetof( OPLinkSettingsData, AESKey), 32*sizeof(uint8_t));
}
void OPLinkSettingsAESKeyGet( uint8_t *NewAESKey )
{
	UAVObjGetDataField(OPLinkSettingsHandle(), (void*)NewAESKey, offsetof( OPLinkSettingsData, AESKey), 32*sizeof(uint8_t));
}


/**
 * @}
 */

