/**
 ******************************************************************************
 * @addtogroup TauLabsCore Tau Labs Core components
 * @{
 * @addtogroup UAVObjectHandling UAVObject handling code
 * @{
 *
 * @file       uavobjectsinit.c
 * @author     The OpenPilot Team, http://www.openpilot.org Copyright (C) 2010.
 * @author     Tau Labs, http://taulabs.org, Copyright (C) 2012-2013
 * @brief      Initialize all objects.
 *             Automatically generated by the UAVObjectGenerator.
 *   
 * @note       This is an automatically generated file.
 *             DO NOT modify manually.
 * @see        The GNU Public License (GPL) Version 3
 *
 *****************************************************************************/
/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */

#include "openpilot.h"
#include "acceldesired.h"
#include "accels.h"
#include "accessorydesired.h"
#include "actuatorcommand.h"
#include "actuatordesired.h"
#include "actuatorsettings.h"
#include "airspeedactual.h"
#include "airspeedsettings.h"
#include "altitudeholddesired.h"
#include "altitudeholdsettings.h"
#include "attitudeactual.h"
#include "attitudesettings.h"
#include "attitudesimulated.h"
#include "baroairspeed.h"
#include "baroaltitude.h"
#include "brushlessgimbalsettings.h"
#include "cameradesired.h"
#include "camerastabsettings.h"
#include "faultsettings.h"
#include "firmwareiapobj.h"
#include "fixedwingairspeeds.h"
#include "fixedwingpathfollowersettings.h"
#include "fixedwingpathfollowersettingscc.h"
#include "fixedwingpathfollowerstatus.h"
#include "flightbatterysettings.h"
#include "flightbatterystate.h"
#include "flightplancontrol.h"
#include "flightplansettings.h"
#include "flightplanstatus.h"
#include "flightstatus.h"
#include "flighttelemetrystats.h"
#include "gcsreceiver.h"
#include "gcstelemetrystats.h"
#include "gpsposition.h"
#include "gpssatellites.h"
#include "gpstime.h"
#include "gpsvelocity.h"
#include "groundpathfollowersettings.h"
#include "groundtruth.h"
#include "gyros.h"
#include "gyrosbias.h"
#include "homelocation.h"
#include "hottsettings.h"
#include "hwcoptercontrol.h"
#include "hwdiscoveryf4.h"
#include "hwflyingf3.h"
#include "hwflyingf4.h"
#include "hwfreedom.h"
#include "hwquanton.h"
#include "hwrevolution.h"
#include "hwrevomini.h"
#include "hwsparky.h"
#include "i2cvm.h"
#include "i2cvmuserprogram.h"
#include "inssettings.h"
#include "insstate.h"
#include "loitercommand.h"
#include "magbias.h"
#include "magnetometer.h"
#include "manualcontrolcommand.h"
#include "manualcontrolsettings.h"
#include "mixersettings.h"
#include "mixerstatus.h"
#include "modulesettings.h"
#include "nedaccel.h"
#include "nedposition.h"
#include "objectpersistence.h"
#include "oplinksettings.h"
#include "oplinkstatus.h"
#include "overosyncsettings.h"
#include "overosyncstats.h"
#include "pathdesired.h"
#include "pathplannersettings.h"
#include "pathstatus.h"
#include "picocsettings.h"
#include "picocstatus.h"
#include "poilocation.h"
#include "positionactual.h"
#include "ratedesired.h"
#include "receiveractivity.h"
#include "relaytuning.h"
#include "relaytuningsettings.h"
#include "sensorsettings.h"
#include "sessionmanaging.h"
#include "sonaraltitude.h"
#include "stabilizationdesired.h"
#include "stabilizationsettings.h"
#include "stateestimation.h"
#include "systemalarms.h"
#include "systemsettings.h"
#include "systemstats.h"
#include "tabletinfo.h"
#include "taskinfo.h"
#include "trimangles.h"
#include "trimanglessettings.h"
#include "txpidsettings.h"
#include "ubloxinfo.h"
#include "velocityactual.h"
#include "velocitydesired.h"
#include "vibrationanalysisoutput.h"
#include "vibrationanalysissettings.h"
#include "vtolpathfollowersettings.h"
#include "vtolpathfollowerstatus.h"
#include "watchdogstatus.h"
#include "waypoint.h"
#include "waypointactive.h"
#include "windvelocityactual.h"


/**
 * Function used to initialize the first instance of each object.
 * This file is automatically updated by the UAVObjectGenerator.
 */
void UAVObjectsInitializeAll()
{
    AccelDesiredInitialize();
    AccelsInitialize();
    AccessoryDesiredInitialize();
    ActuatorCommandInitialize();
    ActuatorDesiredInitialize();
    ActuatorSettingsInitialize();
    AirspeedActualInitialize();
    AirspeedSettingsInitialize();
    AltitudeHoldDesiredInitialize();
    AltitudeHoldSettingsInitialize();
    AttitudeActualInitialize();
    AttitudeSettingsInitialize();
    AttitudeSimulatedInitialize();
    BaroAirspeedInitialize();
    BaroAltitudeInitialize();
    BrushlessGimbalSettingsInitialize();
    CameraDesiredInitialize();
    CameraStabSettingsInitialize();
    FaultSettingsInitialize();
    FirmwareIAPObjInitialize();
    FixedWingAirspeedsInitialize();
    FixedWingPathFollowerSettingsInitialize();
    FixedWingPathFollowerSettingsCCInitialize();
    FixedWingPathFollowerStatusInitialize();
    FlightBatterySettingsInitialize();
    FlightBatteryStateInitialize();
    FlightPlanControlInitialize();
    FlightPlanSettingsInitialize();
    FlightPlanStatusInitialize();
    FlightStatusInitialize();
    FlightTelemetryStatsInitialize();
    GCSReceiverInitialize();
    GCSTelemetryStatsInitialize();
    GPSPositionInitialize();
    GPSSatellitesInitialize();
    GPSTimeInitialize();
    GPSVelocityInitialize();
    GroundPathFollowerSettingsInitialize();
    GroundTruthInitialize();
    GyrosInitialize();
    GyrosBiasInitialize();
    HomeLocationInitialize();
    HoTTSettingsInitialize();
    HwCopterControlInitialize();
    HwDiscoveryF4Initialize();
    HwFlyingF3Initialize();
    HwFlyingF4Initialize();
    HwFreedomInitialize();
    HwQuantonInitialize();
    HwRevolutionInitialize();
    HwRevoMiniInitialize();
    HwSparkyInitialize();
    I2CVMInitialize();
    I2CVMUserProgramInitialize();
    INSSettingsInitialize();
    INSStateInitialize();
    LoiterCommandInitialize();
    MagBiasInitialize();
    MagnetometerInitialize();
    ManualControlCommandInitialize();
    ManualControlSettingsInitialize();
    MixerSettingsInitialize();
    MixerStatusInitialize();
    ModuleSettingsInitialize();
    NedAccelInitialize();
    NEDPositionInitialize();
    ObjectPersistenceInitialize();
    OPLinkSettingsInitialize();
    OPLinkStatusInitialize();
    OveroSyncSettingsInitialize();
    OveroSyncStatsInitialize();
    PathDesiredInitialize();
    PathPlannerSettingsInitialize();
    PathStatusInitialize();
    PicoCSettingsInitialize();
    PicoCStatusInitialize();
    PoiLocationInitialize();
    PositionActualInitialize();
    RateDesiredInitialize();
    ReceiverActivityInitialize();
    RelayTuningInitialize();
    RelayTuningSettingsInitialize();
    SensorSettingsInitialize();
    SessionManagingInitialize();
    SonarAltitudeInitialize();
    StabilizationDesiredInitialize();
    StabilizationSettingsInitialize();
    StateEstimationInitialize();
    SystemAlarmsInitialize();
    SystemSettingsInitialize();
    SystemStatsInitialize();
    TabletInfoInitialize();
    TaskInfoInitialize();
    TrimAnglesInitialize();
    TrimAnglesSettingsInitialize();
    TxPIDSettingsInitialize();
    UBloxInfoInitialize();
    VelocityActualInitialize();
    VelocityDesiredInitialize();
    VibrationAnalysisOutputInitialize();
    VibrationAnalysisSettingsInitialize();
    VtolPathFollowerSettingsInitialize();
    VtolPathFollowerStatusInitialize();
    WatchdogStatusInitialize();
    WaypointInitialize();
    WaypointActiveInitialize();
    WindVelocityActualInitialize();
}

/**
 * @}
 * @}
 */
